// @ts-nocheck
import React,{useCallback,useContext,useEffect,useMemo,useState} from 'react';
import {Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {allowScreenCaptureAsync,preventScreenCaptureAsync} from 'expo-screen-capture';
import {apiRequest,apiUpload,openAuthenticatedFile} from '../api/client';
import {AuthContext} from '../context/AuthContext';
import {AppButton,AppDialog,EmptyState,Panel} from '../ui/components';
import {colors} from '../ui/theme';
import AccountabilityReportView from './AccountabilityReportView';
import FeatureTour, {type TourStep} from '../ui/FeatureTour';
import {useSectionTour} from '../ui/useSectionTour';

const PRINT_AREA_ID='accountability-print-area';
// A área de impressão vive dentro de um ScrollView (overflow:scroll na web), que
// recorta para o que está visível na rolagem atual. Um portal direto para
// document.body escapa desse recorte para a impressão sair completa.
const PrintPortal=({children}:{children:React.ReactNode})=>{
 if(Platform.OS!=='web'||typeof document==='undefined')return null;
 const{createPortal}=require('react-dom');
 return createPortal(children,document.body);
};

type Expense={id?:string;provider:string;purpose:string;serviceDate:string;amountCents:number;has_receipt?:boolean;receipt_file_name?:string;receipt_mime_type?:string;has_proof?:boolean;proof_file_name?:string;proof_mime_type?:string};
type Draft={referenceMonth:string;periodStart:string;periodEnd:string;paidUnits:number;exemptUnits:number;unpaidUnits:number;receivedAmountCents:number;bankBalanceCents:number;expenses:Expense[];sourceFileName?:string;city:string;sindicoName:string;subsindicoName:string;fiscalCouncil1Name:string;fiscalCouncil2Name:string};
type Report={id:string;reference_month:string;period_start:string;period_end:string;origin:string;received_amount_cents:number;bank_balance_cents?:number|null;total_expenses_cents:number;balance_cents:number;paid_units:number;exempt_units:number;unpaid_units:number;source:string;city?:string|null;sindico_name?:string|null;subsindico_name?:string|null;fiscal_council_1_name?:string|null;fiscal_council_2_name?:string|null};
const blankExpense=():Expense=>({provider:'',purpose:'',serviceDate:'',amountCents:0});
const empty=(user?:any):Draft=>({referenceMonth:'',periodStart:'',periodEnd:'',paidUnits:0,exemptUnits:0,unpaidUnits:0,receivedAmountCents:0,bankBalanceCents:0,expenses:[blankExpense()],city:'',sindicoName:user?.role==='sindico'?(user?.fullName||''):'',subsindicoName:user?.role==='subsindico'?(user?.fullName||''):'',fiscalCouncil1Name:'',fiscalCouncil2Name:''});
const brl=(n:number)=>(Number(n)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const cents=(value:string)=>Math.round((Number(value.replace(/\./g,'').replace(',','.').replace(/[^\d.]/g,''))||0)*100);
const signedCents=(value:string)=>Math.round((Number(value.replace(/\./g,'').replace(',','.').replace(/[^\d.-]/g,''))||0)*100);
const money=(n:number)=>brl(Number(n||0));
const displayMonth=(value:string)=>{const match=String(value||'').match(/^(\d{4})-(\d{2})/);return match?`${match[2]}/${match[1]}`:value};
const apiMonth=(value:string)=>{const match=String(value||'').match(/^(\d{2})\/(\d{4})$/);return match?`${match[2]}-${match[1]}`:value};
const displayDate=(value:string)=>{const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return match?`${match[3]}/${match[2]}/${match[1]}`:value};

export default function Accountability({navigation}:any){
 (styles as any).negative={color:colors.red};
 const{userToken,user}=useContext(AuthContext);const manager=user?.role==='sindico'||user?.role==='subsindico';const{scrollRef,tourOpen,registerSection,scrollToSection,openTour,closeTour,isActive}=useSectionTour();const[items,setItems]=useState<Report[]>([]);const[draft,setDraft]=useState<Draft>(empty(user));const[editId,setEditId]=useState<string|null>(null);const[receiptFiles,setReceiptFiles]=useState<Array<any|null>>([]);const[proofFiles,setProofFiles]=useState<Array<any|null>>([]);const[selected,setSelected]=useState<(Report&{expenses:Expense[]})|null>(null);const[source,setSource]=useState<'manual'|'pdf'>('manual');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[dialog,setDialog]=useState<{title:string;message:string;tone:'info'|'success'|'error';confirmLabel?:string;cancelLabel?:string;onConfirm?:()=>void}|null>(null);
 const readingReport=Boolean(selected);
 const total=useMemo(()=>draft.expenses.reduce((sum,item)=>sum+Number(item.amountCents||0),0),[draft.expenses]);
 const load=useCallback(async()=>{if(!userToken)return;try{setItems((await apiRequest<{reports:Report[]}>('/accountability',userToken)).reports)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar')}},[userToken]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(readingReport){allowScreenCaptureAsync('accountability-view')}else{preventScreenCaptureAsync('accountability-view')}},[readingReport]);
 useEffect(()=>()=>{preventScreenCaptureAsync('accountability-view')},[]);
 useEffect(()=>{if(Platform.OS!=='web')return;if(document.getElementById('accountability-print-style'))return;const style=document.createElement('style');style.id='accountability-print-style';style.textContent=`#${PRINT_AREA_ID}{display:none}@media print{body *{visibility:hidden}#${PRINT_AREA_ID}{display:block;position:absolute;left:0;top:0;width:100%}#${PRINT_AREA_ID} *{visibility:visible;-webkit-print-color-adjust:exact;print-color-adjust:exact}}`;document.head.appendChild(style)},[]);
 useEffect(()=>{if(Platform.OS!=='web')return;const stop=(event:KeyboardEvent)=>{if(readingReport)return;if(event.key==='PrintScreen'||(event.ctrlKey&&['p','s'].includes(event.key.toLowerCase()))){event.preventDefault();setError('Captura, impressão e salvamento desta tela não são permitidos.')}};document.addEventListener('keydown',stop);return()=>document.removeEventListener('keydown',stop)},[readingReport]);
 const field=(key:keyof Draft,value:any)=>setDraft(current=>({...current,[key]:value}));
 const expense=(index:number,key:keyof Expense,value:any)=>setDraft(current=>({...current,expenses:current.expenses.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const pick=async()=>{if(!userToken)return;const result=await DocumentPicker.getDocumentAsync({type:'application/pdf',copyToCacheDirectory:true});if(result.canceled)return;setBusy(true);setError('');try{const asset=result.assets[0];const uploadFile=Platform.OS==='web'&&asset.file?asset.file:{uri:asset.uri,name:asset.name,mimeType:asset.mimeType||'application/pdf'};const response=await apiUpload<{draft:Draft;warnings:string[]}>('/accountability/parse-pdf',userToken,uploadFile);setDraft({...response.draft,referenceMonth:displayMonth(response.draft.referenceMonth),periodStart:displayDate(response.draft.periodStart),periodEnd:displayDate(response.draft.periodEnd),bankBalanceCents:0,expenses:response.draft.expenses.length?response.draft.expenses:[blankExpense()]});setSource('pdf');if(response.warnings.length)setError(response.warnings.join(' '))}catch(e){setError(e instanceof Error?e.message:'Falha ao ler PDF')}finally{setBusy(false)}};
 const pickExpenseFile=async(index:number,kind:'receipt'|'proof')=>{const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/jpeg','image/png','image/webp'],copyToCacheDirectory:true});if(result.canceled)return;const setter=kind==='receipt'?setReceiptFiles:setProofFiles;setter(current=>{const next=[...current];next[index]=result.assets[0];return next})};
 const uploadExpenseFile=async(expenseId:string,kind:'receipt'|'proof',file:any)=>{const uploadFile=Platform.OS==='web'&&file.file?file.file:{uri:file.uri,name:file.name,mimeType:file.mimeType};await apiUpload(`/accountability-attachments/${expenseId}/${kind}`,userToken,uploadFile)};
 const save=async()=>{if(!userToken)return;setBusy(true);setError('');try{const path=editId?`/accountability/${editId}`:'/accountability';const response=await apiRequest<{report:{id:string;expenses:Expense[]}}>(path,userToken,{method:editId?'PUT':'POST',body:JSON.stringify({...draft,referenceMonth:apiMonth(draft.referenceMonth),source})});await apiRequest(`/accountability/${response.report.id}/bank-balance`,userToken,{method:'PATCH',body:JSON.stringify({bankBalanceCents:draft.bankBalanceCents})});for(let i=0;i<response.report.expenses.length;i++){const expenseId=response.report.expenses[i].id;if(!expenseId)continue;if(receiptFiles[i])await uploadExpenseFile(expenseId,'receipt',receiptFiles[i]);if(proofFiles[i])await uploadExpenseFile(expenseId,'proof',proofFiles[i])}setDraft(empty(user));setEditId(null);setSelected(null);setReceiptFiles([]);setProofFiles([]);setSource('manual');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar')}finally{setBusy(false)}};
 const view=async(id:string)=>{if(!userToken)return;setBusy(true);try{setSelected((await apiRequest<{report:Report&{expenses:Expense[]}}>(`/accountability/${id}`,userToken)).report)}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir prestação')}finally{setBusy(false)}};
 const startEdit=()=>{if(!selected)return;const report=selected as any;setDraft({referenceMonth:displayMonth(report.reference_month),periodStart:displayDate(report.period_start),periodEnd:displayDate(report.period_end),paidUnits:report.paid_units,exemptUnits:report.exempt_units,unpaidUnits:report.unpaid_units,receivedAmountCents:Number(report.received_amount_cents),bankBalanceCents:Number(report.bank_balance_cents||0),expenses:report.expenses,city:report.city||'',sindicoName:report.sindico_name||(user?.role==='sindico'?(user?.fullName||''):''),subsindicoName:report.subsindico_name||(user?.role==='subsindico'?(user?.fullName||''):''),fiscalCouncil1Name:report.fiscal_council_1_name||'',fiscalCouncil2Name:report.fiscal_council_2_name||''});setEditId(report.id);setSource(report.source);setSelected(null)};
 const removeReport=()=>{if(!selected||!userToken)return;setDialog({title:'Confirmar exclusão',message:'Esta ação também excluirá as despesas e os anexos. Deseja continuar?',tone:'error',confirmLabel:'Excluir',cancelLabel:'Cancelar',onConfirm:async()=>{setDialog(null);try{await apiRequest(`/accountability/${selected.id}`,userToken,{method:'DELETE'});setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir')}}})};
 const hasFile=(item:Expense,kind:'receipt'|'proof')=>Boolean(kind==='receipt'?item.has_receipt:item.has_proof);
 const fileNameFor=(item:Expense,kind:'receipt'|'proof')=>kind==='receipt'?item.receipt_file_name:item.proof_file_name;
 const mimeFor=(item:Expense,kind:'receipt'|'proof')=>kind==='receipt'?item.receipt_mime_type:item.proof_mime_type;
 const openFile=(item:Expense,kind:'receipt'|'proof')=>{const name=fileNameFor(item,kind);return userToken&&item.id&&name&&openAuthenticatedFile(`/accountability-attachments/${item.id}/${kind}`,userToken,name,mimeFor(item,kind)||'application/octet-stream')};
 const attachExisting=async(item:Expense,kind:'receipt'|'proof')=>{if(!userToken||!item.id)return;const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/jpeg','image/png','image/webp'],copyToCacheDirectory:true});if(result.canceled)return;await uploadExpenseFile(item.id,kind,result.assets[0]);await view(selected!.id)};
 const removeFile=(item:Expense,kind:'receipt'|'proof',index?:number)=>{if(!userToken||!item.id)return;const label=kind==='receipt'?'recibo':'comprovante de pagamento';const fileName=kind==='receipt'?item.receipt_file_name:item.proof_file_name;setDialog({title:'Confirmar exclusão',message:`Excluir o ${label}${fileName?` "${fileName}"`:''} de "${item.provider}"? Essa ação não pode ser desfeita.`,tone:'error',confirmLabel:'Excluir',cancelLabel:'Cancelar',onConfirm:async()=>{setDialog(null);try{await apiRequest(`/accountability-attachments/${item.id}/${kind}`,userToken,{method:'DELETE'});if(typeof index==='number')setDraft(current=>({...current,expenses:current.expenses.map((e,i)=>i===index?{...e,[kind==='receipt'?'has_receipt':'has_proof']:false}:e)}));if(selected)await view(selected.id);setDialog({title:'Sucesso',message:`${kind==='receipt'?'Recibo':'Comprovante de pagamento'} excluído com sucesso.`,tone:'success'})}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir anexo')}}})};
 const managerTourSteps:TourStep[]=[
  {key:'actions',title:'Importar PDF ou começar do zero',description:'"Importar PDF" tenta extrair automaticamente mês, período, valores e despesas de um PDF de prestação de contas e preenche o formulário abaixo pra você revisar antes de salvar. "Novo preenchimento" limpa tudo pra digitar manualmente. O campo "Saldo bancário da competência" é o saldo real informado pelo banco naquele mês — fica separado do saldo calculado (recebido menos despesas) e só é exibido ao proprietário quando preenchido.'},
  {key:'form',title:'Dados da prestação',description:'Mês no formato MM/AAAA, período de início e fim, quantidade de apartamentos pagos/isentos/não pagos e total recebido no mês. Cidade e os nomes de síndico, subsíndico e dos dois membros do conselho fiscal são usados na formatação do relatório impresso/PDF gerado a partir dessa prestação.'},
  {key:'expenses',title:'Despesas do mês',description:'Cada linha é uma despesa: empresa ou pessoa, objetivo do serviço, data e valor. Recibo e comprovante de pagamento são opcionais e podem ser anexados em PDF, JPEG, PNG ou WEBP por despesa. O total das despesas e o saldo do mês (recebido menos despesas) são recalculados automaticamente conforme você edita.'},
  {key:'history',title:'Histórico',description:'Todas as prestações já salvas, com receita, despesas, saldo, quantidade de apartamentos pagos/isentos/não pagos e a origem de cada uma (PDF importado ou preenchimento manual).'},
  {key:'detail',title:'Relatório aberto',description:'Depois de tocar num card do histórico, o relatório completo aparece aqui, com opção de imprimir (na web), "Editar prestação" (recarrega os dados no formulário acima) ou "Excluir prestação" — excluir também apaga as despesas e os anexos dessa prestação, sem volta. Dá pra substituir ou excluir o recibo/comprovante de cada prestador individualmente.'},
  {key:'manage',title:'Gerenciar prestações e anexos',description:'Atalho pra reabrir rapidamente qualquer mês já salvo direto na visão de edição e gerenciamento de anexos, sem precisar rolar até o histórico.'},
 ];
 const residentTourSteps:TourStep[]=[
  {key:'reports',title:'Prestações de contas',description:'Cada card é um mês fechado, com receita, despesas e o saldo da prestação daquele período. Toque num card pra abrir o relatório completo. Se você é proprietário, também aparece o saldo bancário informado pela administração, quando preenchido.'},
  {key:'detail',title:'Relatório do mês',description:'Mostra o detalhamento completo da prestação escolhida, com opção de impressão na web. Em "Anexos por prestador" você pode visualizar o recibo e o comprovante de pagamento de cada despesa, quando a administração anexou — aqui é só consulta, não dá pra anexar ou excluir.'},
 ];
 const tourSteps=manager?managerTourSteps:residentTourSteps;
 if(!manager)return <><ScrollView ref={scrollRef} contentContainerStyle={styles.container}><View style={styles.headerRow}><View style={styles.grow}><Text style={styles.eyebrow}>FINANCEIRO</Text><Text style={styles.title}>Prestação de contas</Text><Text style={styles.subtitle}>Visualização protegida de {user?.condominiumName||'seu condomínio'}. Selecione o mês para consultar.</Text></View><Pressable onPress={openTour} style={styles.tourButton}><Text style={styles.tourButtonText}>? Tour desta tela</Text></Pressable></View><View ref={registerSection('reports')} style={[isActive('reports')&&styles.tourHighlight]}>{error?<Text style={styles.error}>{error}</Text>:null}{items.map(item=><Pressable key={item.id} onPress={()=>view(item.id)} style={styles.card}><Text style={styles.cardTitle}>{item.reference_month.slice(0,7)} · {item.origin}</Text><Text>Receita: {brl(item.received_amount_cents)} · Despesas: {brl(item.total_expenses_cents)}</Text><Text style={[styles.balance,Number(item.balance_cents)<0&&styles.negative]}>Saldo da prestação: {brl(item.balance_cents)}</Text>{user?.role==='proprietario'&&item.bank_balance_cents!=null?<Text style={[styles.balance,Number(item.bank_balance_cents)<0&&styles.negative]}>Saldo bancário: {brl(item.bank_balance_cents)}</Text>:null}</Pressable>)}</View>{selected?<View ref={registerSection('detail')} style={[isActive('detail')&&styles.tourHighlight]}><AccountabilityReportView report={selected}/>{Platform.OS==='web'?<PrintPortal><AccountabilityReportView report={selected} printId={PRINT_AREA_ID}/></PrintPortal>:null}{Platform.OS==='web'?<AppButton title="Imprimir" onPress={()=>window.print()}/>:null}{user?.role==='proprietario'&&selected.bank_balance_cents!=null?<Panel><Text style={[styles.balance,Number(selected.bank_balance_cents)<0&&styles.negative]}>Saldo bancário: {brl(selected.bank_balance_cents)}</Text></Panel>:null}<Panel><Text style={styles.heading}>Anexos por prestador</Text>{selected.expenses.map(item=><View key={item.id} style={styles.expense}><Text style={styles.cardTitle}>{item.provider}</Text>{hasFile(item,'receipt')?<Pressable onPress={()=>openFile(item,'receipt')}><Text style={styles.add}>Visualizar recibo: {item.receipt_file_name}</Text></Pressable>:<Text>Sem recibo</Text>}{hasFile(item,'proof')?<Pressable onPress={()=>openFile(item,'proof')}><Text style={styles.add}>Visualizar comprovante: {item.proof_file_name}</Text></Pressable>:<Text>Sem comprovante</Text>}</View>)}</Panel></View>:null}</ScrollView><FeatureTour steps={tourSteps} visible={tourOpen} onClose={closeTour} onStepChange={step=>scrollToSection(step.key)}/></>;
 return <><ScrollView ref={scrollRef} contentContainerStyle={styles.container}>
  <View style={styles.headerRow}><View style={styles.grow}><Text style={styles.eyebrow}>FINANCEIRO</Text><Text style={styles.title}>Prestação de contas</Text><Text style={styles.subtitle}>Dados exclusivos de {user?.condominiumName||'seu condomínio'}. Importe um PDF ou preencha manualmente e revise antes de salvar.</Text></View><Pressable onPress={openTour} style={styles.tourButton}><Text style={styles.tourButtonText}>? Tour desta tela</Text></Pressable></View>
  <Panel><View ref={registerSection('actions')} style={[isActive('actions')&&styles.tourHighlight]}><View style={styles.actions}><AppButton title="Importar PDF" onPress={pick} disabled={busy}/><AppButton title="Novo preenchimento" onPress={()=>{setDraft(empty(user));setEditId(null);setSource('manual');setError('')}} disabled={busy}/></View><Input label="Saldo bancário da competência (R$)" value={money(draft.bankBalanceCents)} onChange={v=>field('bankBalanceCents',signedCents(v))}/></View>
   <View ref={registerSection('form')} style={[isActive('form')&&styles.tourHighlight]}><Text style={styles.origin}>Origem: {user?.condominiumName||'Condomínio logado'}</Text><View style={styles.grid}><Input label="Mês (MM/AAAA)" value={draft.referenceMonth} onChange={v=>field('referenceMonth',v)}/><Input label="Início (DD/MM/AAAA)" value={draft.periodStart} onChange={v=>field('periodStart',v)}/><Input label="Fim (DD/MM/AAAA)" value={draft.periodEnd} onChange={v=>field('periodEnd',v)}/><Input label="Apartamentos pagos" value={String(draft.paidUnits)} onChange={v=>field('paidUnits',Number(v)||0)}/><Input label="Apartamentos isentos" value={String(draft.exemptUnits)} onChange={v=>field('exemptUnits',Number(v)||0)}/><Input label="Apartamentos não pagos" value={String(draft.unpaidUnits)} onChange={v=>field('unpaidUnits',Number(v)||0)}/><Input label="Total recebido (R$)" value={money(draft.receivedAmountCents)} onChange={v=>field('receivedAmountCents',cents(v))}/><Input label="Cidade" value={draft.city} onChange={v=>field('city',v)}/><Input label="Nome do Síndico" value={draft.sindicoName} onChange={v=>field('sindicoName',v)}/><Input label="Nome do Subsíndico" value={draft.subsindicoName} onChange={v=>field('subsindicoName',v)}/><Input label="Conselho Fiscal 1" value={draft.fiscalCouncil1Name} onChange={v=>field('fiscalCouncil1Name',v)}/><Input label="Conselho Fiscal 2" value={draft.fiscalCouncil2Name} onChange={v=>field('fiscalCouncil2Name',v)}/></View></View>
   <View ref={registerSection('expenses')} style={[isActive('expenses')&&styles.tourHighlight]}><Text style={styles.heading}>Despesas</Text>{draft.expenses.map((item,index)=><View key={index} style={styles.expense}><Input label="Empresa ou pessoa" value={item.provider} onChange={v=>expense(index,'provider',v)}/><Input label="Objetivo do serviço" value={item.purpose} onChange={v=>expense(index,'purpose',v)}/><Input label="Data (DD/MM/AAAA)" value={item.serviceDate} onChange={v=>expense(index,'serviceDate',v)}/><Input label="Valor (R$)" value={money(item.amountCents)} onChange={v=>expense(index,'amountCents',cents(v))}/><View style={styles.attachRow}><View style={styles.attachCol}><Pressable onPress={()=>pickExpenseFile(index,'receipt')}><Text style={styles.add}>{receiptFiles[index]?`Recibo selecionado: ${receiptFiles[index].name}`:item.has_receipt?`Recibo atual: ${item.receipt_file_name} (toque para substituir)`:'+ Anexar recibo (opcional)'}</Text></Pressable>{item.has_receipt&&!receiptFiles[index]?<Pressable onPress={()=>removeFile(item,'receipt',index)}><Text style={styles.remove}>Excluir recibo</Text></Pressable>:null}</View><View style={styles.attachCol}><Pressable onPress={()=>pickExpenseFile(index,'proof')}><Text style={styles.add}>{proofFiles[index]?`Comprovante selecionado: ${proofFiles[index].name}`:item.has_proof?`Comprovante atual: ${item.proof_file_name} (toque para substituir)`:'+ Anexar comprovante (opcional)'}</Text></Pressable>{item.has_proof&&!proofFiles[index]?<Pressable onPress={()=>removeFile(item,'proof',index)}><Text style={styles.remove}>Excluir comprovante</Text></Pressable>:null}</View></View><Pressable onPress={()=>{setDraft(current=>({...current,expenses:current.expenses.filter((_,i)=>i!==index)}));setReceiptFiles(current=>current.filter((_,i)=>i!==index));setProofFiles(current=>current.filter((_,i)=>i!==index))}}><Text style={styles.remove}>Remover</Text></Pressable></View>)}
   <Pressable onPress={()=>setDraft(current=>({...current,expenses:[...current.expenses,blankExpense()]}))}><Text style={styles.add}>+ Adicionar despesa</Text></Pressable><View style={styles.totals}><Text>Total das despesas: {brl(total)}</Text><Text style={[styles.balance,draft.receivedAmountCents-total<0&&styles.negative]}>Saldo do mês: {brl(draft.receivedAmountCents-total)}</Text><Text style={[styles.balance,draft.bankBalanceCents<0&&styles.negative]}>Saldo bancário: {brl(draft.bankBalanceCents)}</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}<AppButton title={busy?'Aguarde...':'Salvar prestação de contas'} onPress={save} disabled={busy}/></View>
  </Panel><View ref={registerSection('history')} style={[isActive('history')&&styles.tourHighlight]}><Text style={styles.heading}>Histórico</Text>{items.length?items.map(item=><View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.reference_month.slice(0,7)} · {item.origin}</Text><Text>Receita: {brl(item.received_amount_cents)} | Despesas: {brl(item.total_expenses_cents)}</Text><Text style={[styles.balance,Number(item.balance_cents)<0&&styles.negative]}>Saldo: {brl(item.balance_cents)}</Text><Text>Pagos: {item.paid_units} · Isentos: {item.exempt_units} · Não pagos: {item.unpaid_units} · {item.source==='pdf'?'PDF':'Manual'}</Text></View>):<EmptyState title="Nenhuma prestação cadastrada" description="Os fechamentos mensais aparecerão aqui."/>}</View>
 {selected?<View ref={registerSection('detail')} style={[isActive('detail')&&styles.tourHighlight]}><AccountabilityReportView report={selected}/>{Platform.OS==='web'?<PrintPortal><AccountabilityReportView report={selected} printId={PRINT_AREA_ID}/></PrintPortal>:null}{Platform.OS==='web'?<AppButton title="Imprimir" onPress={()=>window.print()}/>:null}<Panel><View style={styles.actions}><AppButton title="Editar prestação" onPress={startEdit}/><AppButton title="Excluir prestação" onPress={removeReport}/></View><Text style={styles.heading}>Anexos por prestador</Text>{selected.expenses.map(item=><View key={item.id} style={styles.expense}><Text style={styles.cardTitle}>{item.provider}</Text><View style={styles.attachRow}><View style={styles.attachCol}>{hasFile(item,'receipt')?<Pressable onPress={()=>openFile(item,'receipt')}><Text style={styles.add}>Visualizar recibo: {item.receipt_file_name}</Text></Pressable>:null}<Pressable onPress={()=>attachExisting(item,'receipt')}><Text style={styles.add}>{hasFile(item,'receipt')?'Substituir recibo':'+ Anexar recibo'}</Text></Pressable>{hasFile(item,'receipt')?<Pressable onPress={()=>removeFile(item,'receipt')}><Text style={styles.remove}>Excluir recibo</Text></Pressable>:null}</View><View style={styles.attachCol}>{hasFile(item,'proof')?<Pressable onPress={()=>openFile(item,'proof')}><Text style={styles.add}>Visualizar comprovante: {item.proof_file_name}</Text></Pressable>:null}<Pressable onPress={()=>attachExisting(item,'proof')}><Text style={styles.add}>{hasFile(item,'proof')?'Substituir comprovante':'+ Anexar comprovante'}</Text></Pressable>{hasFile(item,'proof')?<Pressable onPress={()=>removeFile(item,'proof')}><Text style={styles.remove}>Excluir comprovante</Text></Pressable>:null}</View></View></View>)}</Panel></View>:null}<View ref={registerSection('manage')} style={[isActive('manage')&&styles.tourHighlight]}><Text style={styles.heading}>Gerenciar prestações e anexos</Text>{items.map(item=><Pressable key={`attachment-${item.id}`} onPress={()=>view(item.id)} style={styles.card}><Text>{item.reference_month.slice(0,7)} · editar, excluir ou gerenciar anexos</Text></Pressable>)}</View>
 <AppDialog visible={Boolean(dialog)} title={dialog?.title||''} message={dialog?.message||''} tone={dialog?.tone} confirmLabel={dialog?.confirmLabel} cancelLabel={dialog?.cancelLabel} onConfirm={dialog?.onConfirm} onClose={()=>setDialog(null)}/>
 </ScrollView><FeatureTour steps={tourSteps} visible={tourOpen} onClose={closeTour} onStepChange={step=>scrollToSection(step.key)}/></>;
}
function Input({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <View style={styles.inputBox}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} style={styles.input}/></View>}
const styles=StyleSheet.create({container:{width:'100%',alignSelf:'center',padding:24,paddingBottom:50},headerRow:{flexDirection:'row',alignItems:'flex-start',gap:12,flexWrap:'wrap'},grow:{flex:1},tourButton:{borderWidth:1,borderColor:colors.primary,borderRadius:20,paddingHorizontal:14,paddingVertical:9,backgroundColor:colors.softBlue},tourButtonText:{color:colors.primaryDark,fontWeight:'900',fontSize:13},tourHighlight:{borderWidth:2,borderColor:colors.primary,borderRadius:16,padding:6,margin:-6},eyebrow:{color:colors.primary,fontWeight:'900'},title:{fontSize:28,fontWeight:'900',color:colors.ink,marginTop:5},subtitle:{color:colors.muted,fontSize:16,marginVertical:10},actions:{flexDirection:'row',gap:10,flexWrap:'wrap',marginBottom:12},origin:{fontWeight:'800',color:colors.ink,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},inputBox:{flexGrow:1,minWidth:190},label:{color:colors.muted,fontWeight:'700',marginBottom:4},input:{borderWidth:1,borderColor:colors.border,borderRadius:8,minHeight:46,paddingHorizontal:10,backgroundColor:'#fff'},heading:{fontSize:19,fontWeight:'900',color:colors.ink,marginTop:22,marginBottom:10},expense:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:12,marginTop:8,gap:8},attachRow:{flexDirection:'row',flexWrap:'wrap',gap:16},attachCol:{gap:4},remove:{color:colors.red,fontWeight:'800'},add:{color:colors.primary,fontWeight:'900',marginVertical:14},totals:{padding:14,backgroundColor:'#f1f5fb',borderRadius:8,gap:5},balance:{fontWeight:'900',color:colors.ink},error:{color:colors.red,marginVertical:10},card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:8,padding:14,marginBottom:10,gap:5},cardTitle:{fontWeight:'900',fontSize:17,color:colors.ink}});
