// @ts-nocheck
import React,{useCallback,useContext,useEffect,useMemo,useState} from 'react';
import {Alert,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {usePreventScreenCapture} from 'expo-screen-capture';
import {apiRequest,apiUpload,openAuthenticatedFile} from '../api/client';
import {AuthContext} from '../context/AuthContext';
import ResponsiveShell from '../ui/ResponsiveShell';
import {AppButton,EmptyState,Panel} from '../ui/components';
import {colors} from '../ui/theme';

type Expense={id?:string;provider:string;purpose:string;serviceDate:string;amountCents:number;has_attachment?:boolean;attachment_name?:string;attachment_mime_type?:string};
type Draft={referenceMonth:string;periodStart:string;periodEnd:string;paidUnits:number;exemptUnits:number;unpaidUnits:number;receivedAmountCents:number;bankBalanceCents:number;expenses:Expense[];sourceFileName?:string};
type Report={id:string;reference_month:string;origin:string;received_amount_cents:number;bank_balance_cents?:number|null;total_expenses_cents:number;balance_cents:number;paid_units:number;exempt_units:number;unpaid_units:number;source:string};
const blankExpense=():Expense=>({provider:'',purpose:'',serviceDate:'',amountCents:0});
const empty=():Draft=>({referenceMonth:'',periodStart:'',periodEnd:'',paidUnits:0,exemptUnits:0,unpaidUnits:0,receivedAmountCents:0,bankBalanceCents:0,expenses:[blankExpense()]});
const brl=(n:number)=>(Number(n)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const cents=(value:string)=>Math.round((Number(value.replace(/\./g,'').replace(',','.').replace(/[^\d.]/g,''))||0)*100);
const signedCents=(value:string)=>Math.round((Number(value.replace(/\./g,'').replace(',','.').replace(/[^\d.-]/g,''))||0)*100);
const money=(n:number)=>brl(Number(n||0));
const displayMonth=(value:string)=>{const match=String(value||'').match(/^(\d{4})-(\d{2})/);return match?`${match[2]}/${match[1]}`:value};
const apiMonth=(value:string)=>{const match=String(value||'').match(/^(\d{2})\/(\d{4})$/);return match?`${match[2]}-${match[1]}`:value};
const displayDate=(value:string)=>{const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return match?`${match[3]}/${match[2]}/${match[1]}`:value};

export default function Accountability({navigation}:any){
 usePreventScreenCapture();
 (styles as any).negative={color:colors.red};
 const{userToken,user}=useContext(AuthContext);const manager=user?.role==='sindico'||user?.role==='subsindico';const[items,setItems]=useState<Report[]>([]);const[draft,setDraft]=useState<Draft>(empty());const[editId,setEditId]=useState<string|null>(null);const[files,setFiles]=useState<Array<any|null>>([]);const[selected,setSelected]=useState<(Report&{expenses:Expense[]})|null>(null);const[source,setSource]=useState<'manual'|'pdf'>('manual');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const total=useMemo(()=>draft.expenses.reduce((sum,item)=>sum+Number(item.amountCents||0),0),[draft.expenses]);
 const load=useCallback(async()=>{if(!userToken)return;try{setItems((await apiRequest<{reports:Report[]}>('/accountability',userToken)).reports)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar')}},[userToken]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(Platform.OS!=='web')return;const stop=(event:KeyboardEvent)=>{if(event.key==='PrintScreen'||(event.ctrlKey&&['p','s'].includes(event.key.toLowerCase()))){event.preventDefault();setError('Captura, impressão e salvamento desta tela não são permitidos.')}};document.addEventListener('keydown',stop);return()=>document.removeEventListener('keydown',stop)},[]);
 const field=(key:keyof Draft,value:any)=>setDraft(current=>({...current,[key]:value}));
 const expense=(index:number,key:keyof Expense,value:any)=>setDraft(current=>({...current,expenses:current.expenses.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const pick=async()=>{if(!userToken)return;const result=await DocumentPicker.getDocumentAsync({type:'application/pdf',copyToCacheDirectory:true});if(result.canceled)return;setBusy(true);setError('');try{const asset=result.assets[0];const uploadFile=Platform.OS==='web'&&asset.file?asset.file:{uri:asset.uri,name:asset.name,mimeType:asset.mimeType||'application/pdf'};const response=await apiUpload<{draft:Draft;warnings:string[]}>('/accountability/parse-pdf',userToken,uploadFile);setDraft({...response.draft,referenceMonth:displayMonth(response.draft.referenceMonth),periodStart:displayDate(response.draft.periodStart),periodEnd:displayDate(response.draft.periodEnd),bankBalanceCents:0,expenses:response.draft.expenses.length?response.draft.expenses:[blankExpense()]});setSource('pdf');if(response.warnings.length)setError(response.warnings.join(' '))}catch(e){setError(e instanceof Error?e.message:'Falha ao ler PDF')}finally{setBusy(false)}};
 const pickExpenseFile=async(index:number)=>{const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/jpeg','image/png','image/webp'],copyToCacheDirectory:true});if(!result.canceled)setFiles(current=>{const next=[...current];next[index]=result.assets[0];return next})};
 const save=async()=>{if(!userToken)return;setBusy(true);setError('');try{const path=editId?`/accountability/${editId}`:'/accountability';const response=await apiRequest<{report:{id:string;expenses:Expense[]}}>(path,userToken,{method:editId?'PUT':'POST',body:JSON.stringify({...draft,referenceMonth:apiMonth(draft.referenceMonth),source})});await apiRequest(`/accountability/${response.report.id}/bank-balance`,userToken,{method:'PATCH',body:JSON.stringify({bankBalanceCents:draft.bankBalanceCents})});for(let i=0;i<response.report.expenses.length;i++){const file=files[i];const expenseId=response.report.expenses[i].id;if(file&&expenseId){const uploadFile=Platform.OS==='web'&&file.file?file.file:{uri:file.uri,name:file.name,mimeType:file.mimeType};await apiUpload(`/accountability-attachments/${expenseId}`,userToken,uploadFile)}}setDraft(empty());setEditId(null);setSelected(null);setFiles([]);setSource('manual');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar')}finally{setBusy(false)}};
 const view=async(id:string)=>{if(!userToken)return;setBusy(true);try{setSelected((await apiRequest<{report:Report&{expenses:Expense[]}}>(`/accountability/${id}`,userToken)).report)}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir prestação')}finally{setBusy(false)}};
 const startEdit=()=>{if(!selected)return;const report=selected as any;setDraft({referenceMonth:displayMonth(report.reference_month),periodStart:displayDate(report.period_start),periodEnd:displayDate(report.period_end),paidUnits:report.paid_units,exemptUnits:report.exempt_units,unpaidUnits:report.unpaid_units,receivedAmountCents:Number(report.received_amount_cents),bankBalanceCents:Number(report.bank_balance_cents||0),expenses:report.expenses});setEditId(report.id);setSource(report.source);setSelected(null)};
 const removeReport=()=>{if(!selected||!userToken)return;Alert.alert('Excluir prestação de contas','Esta ação também excluirá as despesas e os anexos. Deseja continuar?',[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:async()=>{try{await apiRequest(`/accountability/${selected.id}`,userToken,{method:'DELETE'});setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir')}}}])};
 const openFile=(item:Expense)=>userToken&&item.id&&item.attachment_name&&openAuthenticatedFile(`/accountability-attachments/${item.id}`,userToken,item.attachment_name,item.attachment_mime_type||'application/octet-stream');
 const attachExisting=async(item:Expense)=>{if(!userToken||!item.id)return;const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/jpeg','image/png','image/webp'],copyToCacheDirectory:true});if(result.canceled)return;const file=result.assets[0];const uploadFile=Platform.OS==='web'&&file.file?file.file:{uri:file.uri,name:file.name,mimeType:file.mimeType};await apiUpload(`/accountability-attachments/${item.id}`,userToken,uploadFile);await view(selected!.id)};
 if(!manager)return <ResponsiveShell activeRoute="Accountability" navigation={navigation}><ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>FINANCEIRO</Text><Text style={styles.title}>Prestação de contas</Text><Text style={styles.subtitle}>Visualização protegida de {user?.condominiumName||'seu condomínio'}. Selecione o mês para consultar.</Text>{error?<Text style={styles.error}>{error}</Text>:null}{items.map(item=><Pressable key={item.id} onPress={()=>view(item.id)} style={styles.card}><Text style={styles.cardTitle}>{item.reference_month.slice(0,7)} · {item.origin}</Text><Text>Receita: {brl(item.received_amount_cents)} · Despesas: {brl(item.total_expenses_cents)}</Text><Text style={[styles.balance,Number(item.balance_cents)<0&&styles.negative]}>Saldo da prestação: {brl(item.balance_cents)}</Text>{user?.role==='proprietario'&&item.bank_balance_cents!=null?<Text style={[styles.balance,Number(item.bank_balance_cents)<0&&styles.negative]}>Saldo bancário: {brl(item.bank_balance_cents)}</Text>:null}</Pressable>)}{selected?<Panel><Text style={styles.heading}>{selected.reference_month.slice(0,7)} · {selected.origin}</Text><Text>Pagos: {selected.paid_units} · Isentos: {selected.exempt_units} · Não pagos: {selected.unpaid_units}</Text><Text style={[styles.balance,Number(selected.balance_cents)<0&&styles.negative]}>Saldo da prestação: {brl(selected.balance_cents)}</Text>{user?.role==='proprietario'&&selected.bank_balance_cents!=null?<Text style={[styles.balance,Number(selected.bank_balance_cents)<0&&styles.negative]}>Saldo bancário: {brl(selected.bank_balance_cents)}</Text>:null}{selected.expenses.map(item=><View key={item.id} style={styles.expense}><Text style={styles.cardTitle}>{item.provider}</Text><Text>{item.purpose} · {item.serviceDate}</Text><Text style={styles.balance}>{brl(item.amountCents)}</Text>{item.has_attachment?<Pressable onPress={()=>openFile(item)}><Text style={styles.add}>Visualizar anexo: {item.attachment_name}</Text></Pressable>:<Text>Sem anexo</Text>}</View>)}</Panel>:null}</ScrollView></ResponsiveShell>;
 return <ResponsiveShell activeRoute="Accountability" navigation={navigation}><ScrollView contentContainerStyle={styles.container}>
  <Text style={styles.eyebrow}>FINANCEIRO</Text><Text style={styles.title}>Prestação de contas</Text><Text style={styles.subtitle}>Dados exclusivos de {user?.condominiumName||'seu condomínio'}. Importe um PDF ou preencha manualmente e revise antes de salvar.</Text>
  <Panel><View style={styles.actions}><AppButton title="Importar PDF" onPress={pick} disabled={busy}/><AppButton title="Novo preenchimento" onPress={()=>{setDraft(empty());setEditId(null);setSource('manual');setError('')}} disabled={busy}/></View><Input label="Saldo bancário da competência (R$)" value={money(draft.bankBalanceCents)} onChange={v=>field('bankBalanceCents',signedCents(v))}/>
   <Text style={styles.origin}>Origem: {user?.condominiumName||'Condomínio logado'}</Text><View style={styles.grid}><Input label="Mês (MM/AAAA)" value={draft.referenceMonth} onChange={v=>field('referenceMonth',v)}/><Input label="Início (DD/MM/AAAA)" value={draft.periodStart} onChange={v=>field('periodStart',v)}/><Input label="Fim (DD/MM/AAAA)" value={draft.periodEnd} onChange={v=>field('periodEnd',v)}/><Input label="Apartamentos pagos" value={String(draft.paidUnits)} onChange={v=>field('paidUnits',Number(v)||0)}/><Input label="Apartamentos isentos" value={String(draft.exemptUnits)} onChange={v=>field('exemptUnits',Number(v)||0)}/><Input label="Apartamentos não pagos" value={String(draft.unpaidUnits)} onChange={v=>field('unpaidUnits',Number(v)||0)}/><Input label="Total recebido (R$)" value={money(draft.receivedAmountCents)} onChange={v=>field('receivedAmountCents',cents(v))}/></View>
   <Text style={styles.heading}>Despesas</Text>{draft.expenses.map((item,index)=><View key={index} style={styles.expense}><Input label="Empresa ou pessoa" value={item.provider} onChange={v=>expense(index,'provider',v)}/><Input label="Objetivo do serviço" value={item.purpose} onChange={v=>expense(index,'purpose',v)}/><Input label="Data (DD/MM/AAAA)" value={item.serviceDate} onChange={v=>expense(index,'serviceDate',v)}/><Input label="Valor (R$)" value={money(item.amountCents)} onChange={v=>expense(index,'amountCents',cents(v))}/><Pressable onPress={()=>setDraft(current=>({...current,expenses:current.expenses.filter((_,i)=>i!==index)}))}><Text style={styles.remove}>Remover</Text></Pressable></View>)}
   <Pressable onPress={()=>setDraft(current=>({...current,expenses:[...current.expenses,blankExpense()]}))}><Text style={styles.add}>+ Adicionar despesa</Text></Pressable><View style={styles.totals}><Text>Total das despesas: {brl(total)}</Text><Text style={[styles.balance,draft.receivedAmountCents-total<0&&styles.negative]}>Saldo do mês: {brl(draft.receivedAmountCents-total)}</Text><Text style={[styles.balance,draft.bankBalanceCents<0&&styles.negative]}>Saldo bancário: {brl(draft.bankBalanceCents)}</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}<AppButton title={busy?'Aguarde...':'Salvar prestação de contas'} onPress={save} disabled={busy}/>
  </Panel><Text style={styles.heading}>Histórico</Text>{items.length?items.map(item=><View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.reference_month.slice(0,7)} · {item.origin}</Text><Text>Receita: {brl(item.received_amount_cents)} | Despesas: {brl(item.total_expenses_cents)}</Text><Text style={[styles.balance,Number(item.balance_cents)<0&&styles.negative]}>Saldo: {brl(item.balance_cents)}</Text><Text>Pagos: {item.paid_units} · Isentos: {item.exempt_units} · Não pagos: {item.unpaid_units} · {item.source==='pdf'?'PDF':'Manual'}</Text></View>):<EmptyState title="Nenhuma prestação cadastrada" description="Os fechamentos mensais aparecerão aqui."/>}
 {selected?<Panel><View style={styles.actions}><AppButton title="Editar prestação" onPress={startEdit}/><AppButton title="Excluir prestação" onPress={removeReport}/></View><Text style={styles.heading}>Anexos por prestador</Text>{selected.expenses.map(item=><View key={item.id} style={styles.expense}><Text style={styles.cardTitle}>{item.provider}</Text>{item.has_attachment?<Pressable onPress={()=>openFile(item)}><Text style={styles.add}>Visualizar {item.attachment_name}</Text></Pressable>:null}<Pressable onPress={()=>attachExisting(item)}><Text style={styles.add}>{item.has_attachment?'Substituir anexo':'+ Anexar imagem ou PDF'}</Text></Pressable></View>)}</Panel>:null}<Text style={styles.heading}>Gerenciar prestações e anexos</Text>{items.map(item=><Pressable key={`attachment-${item.id}`} onPress={()=>view(item.id)} style={styles.card}><Text>{item.reference_month.slice(0,7)} · editar, excluir ou gerenciar anexos</Text></Pressable>)}
 </ScrollView></ResponsiveShell>;
}
function Input({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <View style={styles.inputBox}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} style={styles.input}/></View>}
const styles=StyleSheet.create({container:{width:'100%',maxWidth:1180,alignSelf:'center',padding:24,paddingBottom:50},eyebrow:{color:colors.primary,fontWeight:'900'},title:{fontSize:28,fontWeight:'900',color:colors.ink,marginTop:5},subtitle:{color:colors.muted,fontSize:16,marginVertical:10},actions:{flexDirection:'row',gap:10,flexWrap:'wrap',marginBottom:12},origin:{fontWeight:'800',color:colors.ink,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},inputBox:{flexGrow:1,minWidth:190},label:{color:colors.muted,fontWeight:'700',marginBottom:4},input:{borderWidth:1,borderColor:colors.border,borderRadius:8,minHeight:46,paddingHorizontal:10,backgroundColor:'#fff'},heading:{fontSize:19,fontWeight:'900',color:colors.ink,marginTop:22,marginBottom:10},expense:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:12,marginTop:8,gap:8},remove:{color:colors.red,fontWeight:'800'},add:{color:colors.primary,fontWeight:'900',marginVertical:14},totals:{padding:14,backgroundColor:'#f1f5fb',borderRadius:8,gap:5},balance:{fontWeight:'900',color:colors.ink},error:{color:colors.red,marginVertical:10},card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:8,padding:14,marginBottom:10,gap:5},cardTitle:{fontWeight:'900',fontSize:17,color:colors.ink}});
