import React, { useCallback, useContext, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiRequest, downloadAuthenticated } from '../api/client';
import { AuthContext } from '../context/AuthContext';
import { AppButton, AppDialog, Panel } from '../ui/components';
import ResponsiveShell from '../ui/ResponsiveShell';
import { colors } from '../ui/theme';
import { brazilianDateToIso, brazilianMonthToIso, formatBrazilianDate, formatBrazilianMonth, maskBrazilianDate, maskBrazilianMonth } from '../utils/date';

type Person={id:string;full_name:string|null;username:string;role:string;unit:string|null;unit_type_name?:string|null;condominium_fee_cents?:number|null;billing_exempt?:boolean;preferred_due_day?:number};
type Preview={referenceMonth:string;validCount:number;totalAmountCents:number;items:Array<Person&{valid:boolean;issues:string[];due_date:string}>};
type Batch={id:string;reference_month:string|null;due_date:string|null;status:string;total_items:number;total_amount_cents:number};
type BatchItem={id:string;payer_name:string;due_date:string;status:string;issues:string[];invoice_id:string|null};
type Dialog={title:string;message:string;tone:'info'|'success'|'error';confirmLabel?:string;cancelLabel?:string;onConfirm?:()=>void};
const money=(c:number)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function BillingSettings({navigation}:any){
 const {userToken}=useContext(AuthContext); const [people,setPeople]=useState<Person[]>([]); const [selected,setSelected]=useState<string[]>([]); const [batches,setBatches]=useState<Batch[]>([]);
 const [referenceMonth,setReferenceMonth]=useState(''); const [description,setDescription]=useState('Taxa condominial - {tipologia}'); const [days,setDays]=useState('30');
 const [beneficiaryName,setBeneficiaryName]=useState(''); const [beneficiaryDocument,setBeneficiaryDocument]=useState('');
 const [boleto,setBoleto]=useState(true); const [pix,setPix]=useState(true); const [afterDue,setAfterDue]=useState(true); const [fineType,setFineType]=useState('NONE'); const [fineValue,setFineValue]=useState('0'); const [interestType,setInterestType]=useState('NONE'); const [interestValue,setInterestValue]=useState('0'); const [discountType,setDiscountType]=useState('NONE'); const [discountValue,setDiscountValue]=useState('0'); const [discountDays,setDiscountDays]=useState('0');
 const [preview,setPreview]=useState<Preview|null>(null); const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const [dialog,setDialog]=useState<Dialog|null>(null);
 const [batchItems,setBatchItems]=useState<Record<string,BatchItem[]>>({}); const [correctedDates,setCorrectedDates]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!userToken)return;try{const [u,c,b]=await Promise.all([apiRequest<any>('/users',userToken),apiRequest<any>('/billing/settings',userToken),apiRequest<any>('/billing/batches',userToken)]);setPeople(u.users.filter((x:Person)=>['proprietario','inquilino'].includes(x.role)&&!x.billing_exempt));setBatches(b.batches);const partials=(b.batches as Batch[]).filter(batch=>batch.status==='partial');const details=await Promise.all(partials.map(async batch=>[batch.id,(await apiRequest<any>(`/billing/batches/${batch.id}/items`,userToken)).items.filter((item:BatchItem)=>item.status==='failed')] as const));const nextItems=Object.fromEntries(details);setBatchItems(nextItems);setCorrectedDates(current=>{const next={...current};details.forEach(([,items])=>items.forEach((item:BatchItem)=>{if(!next[item.id])next[item.id]=formatBrazilianDate(item.due_date)}));return next});setBeneficiaryName(c.condominium?.name||'');setBeneficiaryDocument(c.condominium?.cnpj||'');const x=c.settings;if(x){setDescription(x.description_template);setBoleto(x.receive_boleto);setPix(x.receive_pix);setAfterDue(x.allow_after_due);setDays(String(x.days_after_due));setFineType(x.fine_type);setFineValue(String(x.fine_value));setInterestType(x.interest_type);setInterestValue(String(x.interest_value));setDiscountType(x.discount_type);setDiscountValue(String(x.discount_value));setDiscountDays(String(x.discount_days));}}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar');}},[userToken]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(notice)setDialog({title:'Tudo certo',message:notice,tone:'success'})},[notice]);
 useEffect(()=>{if(error)setDialog({title:'Não foi possível concluir',message:error,tone:'error'})},[error]);
 const save=async()=>{if(!userToken)return;setLoading(true);setError('');try{await apiRequest('/billing/settings',userToken,{method:'PUT',body:JSON.stringify({descriptionTemplate:description,receiveBoleto:boleto,receivePix:pix,allowAfterDue:afterDue,daysAfterDue:+days,fineType,fineValue:+fineValue.replace(',','.'),interestType,interestValue:+interestValue.replace(',','.'),discountType,discountValue:+discountValue.replace(',','.'),discountDays:+discountDays})});setNotice('Configuração salva.');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar')}finally{setLoading(false)}};
 const validate=async()=>{const referenceMonthIso=brazilianMonthToIso(referenceMonth);if(!userToken||!referenceMonthIso)return;setLoading(true);try{setPreview(await apiRequest('/billing/batches/preview',userToken,{method:'POST',body:JSON.stringify({referenceMonth:referenceMonthIso,userIds:selected})}));}catch(e){setError(e instanceof Error?e.message:'Falha ao validar')}finally{setLoading(false)}};
 const draft=async()=>{const referenceMonthIso=brazilianMonthToIso(referenceMonth);if(!userToken||!preview||!referenceMonthIso)return;setLoading(true);try{const r=await apiRequest<any>('/billing/batches',userToken,{method:'POST',body:JSON.stringify({referenceMonth:referenceMonthIso,description,userIds:preview.items.filter(i=>i.valid).map(i=>i.id)})});setNotice(r.message);setPreview(null);setSelected([]);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar lote')}finally{setLoading(false)}};
 const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const confirmBatch=async(id:string)=>{if(!userToken)return;setLoading(true);try{const r=await apiRequest<any>(`/billing/batches/${id}/confirm`,userToken,{method:'POST'});setNotice(r.message);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao confirmar')}finally{setLoading(false)}};
 const executeIssueBatch=async(id:string)=>{if(!userToken)return;setDialog(null);setLoading(true);setError('');setNotice('');try{const r=await apiRequest<any>(`/billing/batches/${id}/issue`,userToken,{method:'POST'});if(r.failed>0)setDialog({title:r.issued>0?'Emissão concluída com pendências':'Boleto não emitido',message:r.message,tone:'error'});else setDialog({title:'Emissão concluída',message:r.message,tone:'success'});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível gerar as cobranças no banco.')}finally{setLoading(false)}};
 const issueBatch=(id:string)=>setDialog({title:'Confirmar emissão dos boletos?',message:'As cobranças deste lote serão enviadas ao Banco Inter e poderão gerar boletos reais. Confira os dados antes de continuar.',tone:'info',confirmLabel:'Sim, emitir boletos',cancelLabel:'Revisar lote',onConfirm:()=>executeIssueBatch(id)});
 const saveFailedDueDate=async(batchId:string,itemId:string)=>{const dueDate=brazilianDateToIso(correctedDates[itemId]||'');if(!userToken||!dueDate)return;setLoading(true);setError('');setNotice('');try{const r=await apiRequest<any>(`/billing/batches/${batchId}/items/${itemId}/due-date`,userToken,{method:'PATCH',body:JSON.stringify({dueDate})});setNotice(r.message);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar o vencimento.')}finally{setLoading(false)}};
 const exportBatch=async(id:string)=>{if(!userToken)return;try{await downloadAuthenticated(`/billing/batches/${id}/export`,userToken,`lote-${id}.xlsx`)}catch(e){setError(e instanceof Error?e.message:'Falha ao exportar')}};
 const options=(value:string,set:(v:string)=>void,items:string[])=><View style={s.row}>{items.map(v=><Pressable key={v} onPress={()=>set(v)} style={[s.option,value===v&&s.on]}><Text style={[s.optionText,value===v&&s.onText]}>{v==='NONE'?'Não aplicar':v==='PERCENT'?'Percentual':v==='FIXED'?'Valor fixo':'% ao mês'}</Text></Pressable>)}</View>;
 return <ResponsiveShell activeRoute="BillingSettings" navigation={navigation}><ScrollView contentContainerStyle={s.container}>
 <Text style={s.eyebrow}>COBRANÇAS</Text><Text style={s.title}>Configuração e emissão em massa</Text><Text style={s.subtitle}>Nome, documento e endereço vêm da pessoa; o valor vem da tipologia. A prévia nunca emite automaticamente.</Text>
 <Panel><Text style={s.heading}>Regras padrão</Text><Text style={s.label}>Recebimento</Text><View style={s.row}><Pressable onPress={()=>setBoleto(!boleto)} style={[s.option,boleto&&s.on]}><Text style={[s.optionText,boleto&&s.onText]}>Boleto</Text></Pressable><Pressable onPress={()=>setPix(!pix)} style={[s.option,pix&&s.on]}><Text style={[s.optionText,pix&&s.onText]}>Pix</Text></Pressable></View><Pressable onPress={()=>setAfterDue(!afterDue)} style={[s.check,afterDue&&s.checkOn]}><Text style={s.optionText}>{afterDue?'✓ ':''}Permitir após vencimento</Text></Pressable><TextInput value={days} onChangeText={setDays} placeholder="Dias após vencimento" keyboardType="number-pad" style={s.input}/>
 <Text style={s.label}>Multa</Text>{options(fineType,setFineType,['NONE','PERCENT','FIXED'])}{fineType!=='NONE'?<TextInput value={fineValue} onChangeText={setFineValue} style={s.input}/>:null}<Text style={s.label}>Juros</Text>{options(interestType,setInterestType,['NONE','PERCENT_MONTH','FIXED'])}{interestType!=='NONE'?<TextInput value={interestValue} onChangeText={setInterestValue} style={s.input}/>:null}<Text style={s.label}>Desconto antecipado</Text>{options(discountType,setDiscountType,['NONE','PERCENT','FIXED'])}{discountType!=='NONE'?<View><TextInput value={discountValue} onChangeText={setDiscountValue} style={s.input}/><TextInput value={discountDays} onChangeText={setDiscountDays} placeholder="Dias antes" style={s.input}/></View>:null}<AppButton title="Salvar configuração" onPress={save} disabled={loading}/></Panel>
 <Panel><Text style={s.heading}>Novo lote mensal</Text><Text style={s.label}>Nome do beneficiário final</Text><TextInput value={beneficiaryName} editable={false} style={[s.input,s.readonly]}/><Text style={s.label}>CPF ou CNPJ do beneficiário</Text><TextInput value={beneficiaryDocument} editable={false} style={[s.input,s.readonly]}/><Text style={s.label}>Descrição na observação do boleto</Text><TextInput value={description} onChangeText={value=>setDescription(value.slice(0,100))} placeholder="Descrição da cobrança" maxLength={100} style={s.input}/><Text style={s.counter}>{description.length}/100 caracteres</Text><Text style={s.label}>Mês de referência</Text><TextInput value={referenceMonth} onChangeText={value=>setReferenceMonth(maskBrazilianMonth(value))} placeholder="MM/AAAA" keyboardType="number-pad" maxLength={7} style={s.input}/><Text style={s.subtitle}>O vencimento será calculado automaticamente pelo dia 10 ou 20 definido no cadastro de cada pessoa.</Text><Pressable onPress={()=>setSelected(selected.length===people.length?[]:people.map(p=>p.id))}><Text style={s.link}>{selected.length===people.length?'Limpar seleção':'Selecionar todas as pessoas'}</Text></Pressable>{people.map(p=><Pressable key={p.id} onPress={()=>toggle(p.id)} style={[s.person,selected.includes(p.id)&&s.personOn]}><View><Text style={s.name}>{selected.includes(p.id)?'✓ ':''}{p.full_name||p.username}</Text><Text style={s.meta}>{p.unit||'Sem unidade'} · {p.unit_type_name||'Sem tipologia'} · vence dia {p.preferred_due_day||10}</Text></View><Text style={s.value}>{p.condominium_fee_cents?money(p.condominium_fee_cents):'Sem valor'}</Text></Pressable>)}<AppButton title="Validar competência" onPress={validate} disabled={loading||!selected.length||!beneficiaryName||!beneficiaryDocument||!description.trim()||!brazilianMonthToIso(referenceMonth)}/>{preview?<View style={s.preview}><Text style={s.heading}>Referência {formatBrazilianMonth(preview.referenceMonth)} · {preview.validCount} válidos · {money(preview.totalAmountCents)}</Text>{preview.items.map(i=><Text key={i.id} style={i.valid?s.ok:s.bad}>{i.valid?'✓':'!'} {i.full_name||i.username} · vencimento {formatBrazilianDate(i.due_date)}{i.issues.length?` — ${i.issues.join(', ')}`:''}</Text>)}<AppButton title="Criar lote mensal" onPress={draft} disabled={!preview.validCount||loading}/></View>:null}</Panel>
 <Text style={s.heading}>Histórico de competências</Text>{batches.map(b=><View key={b.id} style={s.batch}><Text style={s.name}>Referência {b.reference_month?formatBrazilianMonth(b.reference_month):'não informada'} · {b.status}</Text><Text style={s.meta}>Vencimento {b.due_date?formatBrazilianDate(b.due_date):'variado'} · {b.total_items} pessoas · {money(Number(b.total_amount_cents))}</Text>{b.status==='partial'?<View style={s.failedBox}><Text style={s.failedTitle}>Boletos não emitidos</Text>{(batchItems[b.id]||[]).map(item=><View key={item.id} style={s.failedItem}><Text style={s.failedName}>{item.payer_name}</Text><Text style={s.failedReason}>{item.issues?.join(' · ')||'A emissão não foi concluída.'}</Text><Text style={s.label}>Novo vencimento</Text><TextInput value={correctedDates[item.id]||''} onChangeText={value=>setCorrectedDates(current=>({...current,[item.id]:maskBrazilianDate(value)}))} placeholder="DD/MM/AAAA" keyboardType="number-pad" maxLength={10} style={s.input}/><AppButton title="Salvar novo vencimento" onPress={()=>saveFailedDueDate(b.id,item.id)} disabled={loading||!brazilianDateToIso(correctedDates[item.id]||'')}/></View>)}</View>:null}<View style={s.row}>{['draft','validated'].includes(b.status)?<Pressable onPress={()=>confirmBatch(b.id)} style={s.smallButton}><Text style={s.link}>Confirmar seleção para o banco</Text></Pressable>:null}{['confirmed','partial'].includes(b.status)?<Pressable onPress={()=>issueBatch(b.id)} style={s.smallButton}><Text style={s.link}>{b.status==='partial'?'Tentar emitir pendências':'Gerar boletos no Banco Inter'}</Text></Pressable>:null}<Pressable onPress={()=>exportBatch(b.id)} style={s.smallButton}><Text style={s.link}>Exportar Excel</Text></Pressable></View></View>)}</ScrollView><AppDialog visible={Boolean(dialog)} title={dialog?.title||''} message={dialog?.message||''} tone={dialog?.tone} confirmLabel={dialog?.confirmLabel} cancelLabel={dialog?.cancelLabel} onConfirm={dialog?.onConfirm} onClose={()=>setDialog(null)}/></ResponsiveShell>;
}
const s=StyleSheet.create({container:{width:'100%',maxWidth:1180,alignSelf:'center',padding:24,paddingBottom:50,gap:14},eyebrow:{color:colors.primary,fontWeight:'900'},title:{color:colors.ink,fontSize: 27,fontWeight:'900'},subtitle:{color:colors.muted,lineHeight: 21},heading:{color:colors.ink,fontSize: 19,fontWeight:'900',marginBottom:10},label:{color:colors.ink,fontWeight:'800',marginBottom:7},input:{minHeight: 52,borderWidth:1,borderColor:colors.border,borderRadius:8,paddingHorizontal:12,marginBottom:10,backgroundColor:'#fff'},readonly:{backgroundColor:'#f2f4f7',color:colors.primaryDark,fontWeight:'800'},counter:{color:colors.muted,fontSize: 14,textAlign:'right',marginTop:-6,marginBottom:10},row:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},option:{borderWidth:1,borderColor:colors.border,borderRadius:8,padding:10},on:{backgroundColor:colors.primary,borderColor:colors.primary},optionText:{color:colors.muted,fontWeight:'800'},onText:{color:'#fff'},check:{padding:10,marginBottom:8,borderRadius:8,backgroundColor:'#f4f6f8'},checkOn:{backgroundColor:colors.softBlue},link:{color:colors.primary,fontWeight:'900',marginBottom:10},person:{flexDirection:'row',justifyContent:'space-between',borderWidth:1,borderColor:colors.border,borderRadius:8,padding:12,marginBottom:7},personOn:{borderColor:colors.primary,backgroundColor:colors.softBlue},name:{color:colors.ink,fontWeight:'900'},meta:{color:colors.muted,marginTop:3},value:{color:colors.primaryDark,fontWeight:'900'},preview:{marginTop:14,borderTopWidth:1,borderTopColor:colors.border,paddingTop:14,gap:5},ok:{color:colors.green,fontWeight:'800',marginVertical:5},bad:{color:colors.red,fontWeight:'800',marginVertical:5},batch:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:8,padding:12,marginBottom:8},failedBox:{marginTop:14,borderWidth:1,borderColor:'#efb2b2',backgroundColor:'#fff7f7',borderRadius:8,padding:12},failedTitle:{color:colors.red,fontSize: 17,fontWeight:'900',marginBottom:8},failedItem:{borderTopWidth:1,borderTopColor:'#f2cccc',paddingTop:10,marginTop:6},failedName:{color:colors.ink,fontWeight:'900'},failedReason:{color:colors.red,lineHeight: 21,marginTop:4,marginBottom:10},importLine:{borderBottomWidth:1,borderBottomColor:colors.border,paddingVertical:6},issue:{color:colors.muted,fontSize: 15,marginLeft:10},smallButton:{padding:8,backgroundColor:colors.softBlue,borderRadius:8,marginTop:10},fileReady:{borderWidth:1,borderColor:colors.primary,borderRadius:8,backgroundColor:colors.softBlue,padding:12,marginBottom:10},importErrorBox:{borderWidth:1,borderColor:'#efb2b2',borderRadius:8,backgroundColor:'#fff3f3',padding:12,marginTop:10}});
