import React,{useCallback,useContext,useEffect,useMemo,useState} from 'react';
import {Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {apiRequest} from '../api/client';
import {AuthContext} from '../context/AuthContext';
import {AppButton,EmptyState,Panel} from '../ui/components';
import ResponsiveShell from '../ui/ResponsiveShell';
import {colors} from '../ui/theme';
import {brazilianDateToIso,formatBrazilianDate,formatBrazilianMonth} from '../utils/date';

type Person={id:string;full_name:string|null;username:string;unit:string|null;role:string};
type DebtRow={id:string;referenceMonth:string;principalCents:number;dueDate:string;daysLate:number;status:string;fineCents:number;interestCents:number;updatedTotalCents:number;open:boolean;paidAt:string|null};
type DebtData={person:Person&{cpf:string};asOf:string;rules:{finePercent:number;dailyInterestPercent:number;legalBasis:string};rows:DebtRow[];totals:{principalCents:number;fineCents:number;interestCents:number;updatedTotalCents:number;openCount:number}};
const money=(c:number)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const todayBr=()=>new Date().toLocaleDateString('pt-BR');
const situation=(row:DebtRow)=>row.status==='paid'?'Pago':row.daysLate>0?'Em atraso':'Em aberto';

export default function Debts({navigation}:any){
 const {userToken,user}=useContext(AuthContext);const manager=['sindico','subsindico'].includes(user?.role||'');
 const [people,setPeople]=useState<Person[]>([]);const [personId,setPersonId]=useState('');const [search,setSearch]=useState('');const [asOf,setAsOf]=useState(todayBr());const [data,setData]=useState<DebtData|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const selected=people.find(person=>person.id===personId);const matches=useMemo(()=>{const term=search.trim().toLocaleLowerCase('pt-BR');return term.length<2?[]:people.filter(person=>(person.full_name||person.username).toLocaleLowerCase('pt-BR').includes(term)).slice(0,8)},[people,search]);
 useEffect(()=>{if(!userToken||!manager)return;apiRequest<any>('/users',userToken).then(response=>setPeople(response.users.filter((person:Person)=>['proprietario','inquilino'].includes(person.role)))).catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar pessoas'))},[manager,userToken]);
 const load=useCallback(async()=>{if(!userToken)return;const currentDate=todayBr();const date=brazilianDateToIso(currentDate);if(!date)return;if(manager&&!personId){setData(null);return}setAsOf(currentDate);setLoading(true);setError('');try{const query=manager?`?userId=${personId}&asOf=${date}`:`?asOf=${date}`;setData(await apiRequest<DebtData>(`/debts${query}`,userToken))}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar os débitos.')}finally{setLoading(false)}},[manager,personId,userToken]);
 useEffect(()=>{if(manager&&!personId)return;load();const timer=setInterval(load,5*60*1000);return()=>clearInterval(timer)},[load,manager,personId]);
 const years=useMemo(()=>data?Array.from(new Set(data.rows.map(row=>row.referenceMonth.slice(0,4)))).sort().reverse():[],[data]);
 return <ResponsiveShell activeRoute="Debts" navigation={navigation}><ScrollView contentContainerStyle={s.container} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}>
  <Text style={s.eyebrow}>FINANCEIRO</Text><Text style={s.title}>Gestão de débitos</Text><Text style={s.subtitle}>Posição atualizada com multa de 2% e mora diária de 0,0333%, calculadas por boleto vencido.</Text>
  {manager?<Panel><Text style={s.heading}>Pessoa</Text>{selected?<View style={s.selected}><View style={s.grow}><Text style={s.selectedName}>✓ {selected.full_name||selected.username}</Text><Text style={s.meta}>{selected.unit||'Sem unidade'}</Text></View><Pressable onPress={()=>{setPersonId('');setSearch('');setData(null)}}><Text style={s.change}>Trocar</Text></Pressable></View>:<><TextInput value={search} onChangeText={setSearch} placeholder="Pesquise pelo nome" style={s.input}/>{search.trim().length>=2?<View style={s.results}>{matches.length?matches.map(person=><Pressable key={person.id} onPress={()=>{setPersonId(person.id);setSearch(person.full_name||person.username)}} style={s.result}><Text style={s.resultName}>{person.full_name||person.username}</Text><Text style={s.meta}>{person.unit||'Sem unidade'}</Text></Pressable>):<Text style={s.meta}>Nenhuma pessoa encontrada.</Text>}</View>:null}</>}<View style={s.autoBox}><Text style={s.autoTitle}>Atualização automática</Text><Text style={s.autoText}>Valores recalculados até {asOf} usando os boletos e vencimentos sincronizados com o Banco Inter.</Text></View>{selected?<View style={s.analyzeAction}><AppButton title={loading?'Analisando débitos...':'Analisar débitos agora'} onPress={load} disabled={loading}/></View>:null}</Panel>:<Panel><View style={s.autoBox}><Text style={s.autoTitle}>Atualização automática</Text><Text style={s.autoText}>Sua posição é recalculada até {asOf} com base nos boletos emitidos.</Text></View><View style={s.analyzeAction}><AppButton title={loading?'Analisando débitos...':'Analisar débitos agora'} onPress={load} disabled={loading}/></View></Panel>}
  {error?<Text style={s.error}>{error}</Text>:null}
  {data?<><View style={s.reportHeader}><Text style={s.reportTitle}>Débitos de {data.person.full_name||data.person.username}</Text><Text style={s.reportDate}>Atualizado até {formatBrazilianDate(data.asOf)}</Text><Text style={s.rule}>Multa de {data.rules.finePercent}% — {data.rules.legalBasis} · Mora de {data.rules.dailyInterestPercent}% ao dia</Text></View><View style={s.summaryRow}><View style={s.summary}><Text style={s.summaryValue}>{data.totals.openCount}</Text><Text style={s.summaryLabel}>parcelas em aberto</Text></View><View style={s.summary}><Text style={s.summaryValue}>{money(data.totals.principalCents)}</Text><Text style={s.summaryLabel}>principal</Text></View><View style={s.summary}><Text style={s.summaryValue}>{money(data.totals.fineCents+data.totals.interestCents)}</Text><Text style={s.summaryLabel}>encargos</Text></View><View style={s.summaryTotal}><Text style={s.summaryTotalValue}>{money(data.totals.updatedTotalCents)}</Text><Text style={s.summaryTotalLabel}>débito atualizado</Text></View></View>{data.rows.length?years.map(year=><View key={year} style={s.year}><Text style={s.yearTitle}>{year}</Text>{data.rows.filter(row=>row.referenceMonth.startsWith(year)).map(row=><View key={row.id} style={[s.debt,row.daysLate>0&&row.open&&s.debtLate,!row.open&&s.debtPaid]}><View style={s.debtTop}><Text style={s.month}>{formatBrazilianMonth(row.referenceMonth)}</Text><Text style={[s.status,row.daysLate>0&&row.open&&s.statusLate,!row.open&&s.statusPaid]}>{situation(row)}</Text></View><View style={s.grid}><View><Text style={s.cellLabel}>Taxa</Text><Text style={s.cellValue}>{money(row.principalCents)}</Text></View><View><Text style={s.cellLabel}>Vencimento</Text><Text style={s.cellValue}>{formatBrazilianDate(row.dueDate)}</Text></View><View><Text style={s.cellLabel}>Dias de atraso</Text><Text style={s.cellValue}>{row.daysLate}</Text></View><View><Text style={s.cellLabel}>Multa 2%</Text><Text style={s.cellValue}>{money(row.fineCents)}</Text></View><View><Text style={s.cellLabel}>Mora 0,0333% a.d.</Text><Text style={s.cellValue}>{money(row.interestCents)}</Text></View><View><Text style={s.cellLabel}>Total atualizado</Text><Text style={s.totalValue}>{money(row.updatedTotalCents)}</Text></View></View></View>)}</View>):<EmptyState title="Nenhuma cobrança encontrada" description="Não há competências registradas para esta pessoa."/>}</>:manager&&personId?null:<EmptyState title="Selecione uma pessoa" description="Pesquise pelo nome para consultar todos os meses e calcular a posição atualizada."/>}
 </ScrollView></ResponsiveShell>;
}

const s=StyleSheet.create({container:{width:'100%',maxWidth:1180,alignSelf:'center',padding:24,paddingBottom:50,gap:14},eyebrow:{color:colors.primary,fontWeight:'900'},title:{color:colors.ink,fontSize: 28,fontWeight:'900'},subtitle:{color:colors.muted,lineHeight: 22},heading:{color:colors.ink,fontSize: 19,fontWeight:'900',marginBottom:10},label:{color:colors.ink,fontWeight:'800',marginBottom:7},input:{minHeight: 52,borderWidth:1,borderColor:colors.border,borderRadius:8,paddingHorizontal:12,backgroundColor:'#fff',marginBottom:10},selected:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:colors.primary,borderRadius:8,backgroundColor:colors.softBlue,padding:12,marginBottom:12},grow:{flex:1},selectedName:{color:colors.primaryDark,fontWeight:'900'},change:{color:colors.primary,fontWeight:'900'},meta:{color:colors.muted,marginTop:3},results:{gap:7,marginBottom:12},result:{borderWidth:1,borderColor:colors.border,borderRadius:8,padding:11},resultName:{color:colors.ink,fontWeight:'900'},autoBox:{borderWidth:1,borderColor:'#b8d6c1',backgroundColor:colors.softGreen,borderRadius:8,padding:11},autoTitle:{color:colors.green,fontWeight:'900'},autoText:{color:colors.muted,lineHeight: 21,marginTop:3},analyzeAction:{marginTop:12},error:{color:colors.red,fontWeight:'800'},reportHeader:{backgroundColor:'#dbeaf7',borderRadius:10,padding:16,alignItems:'center'},reportTitle:{color:colors.ink,fontSize: 20,fontWeight:'900',textAlign:'center'},reportDate:{color:colors.primaryDark,fontWeight:'800',marginTop:5},rule:{color:colors.muted,textAlign:'center',marginTop:6},summaryRow:{flexDirection:'row',flexWrap:'wrap',gap:9},summary:{flexGrow:1,minWidth:170,borderWidth:1,borderColor:colors.border,borderRadius:8,backgroundColor:'#fff',padding:13},summaryValue:{color:colors.ink,fontSize: 19,fontWeight:'900'},summaryLabel:{color:colors.muted,marginTop:3},summaryTotal:{flexGrow:1,minWidth:190,borderRadius:8,backgroundColor:colors.red,padding:13},summaryTotalValue:{color:'#fff',fontSize: 20,fontWeight:'900'},summaryTotalLabel:{color:'#fff',marginTop:3},year:{gap:8},yearTitle:{color:colors.ink,fontSize: 19,fontWeight:'900',marginTop:6},debt:{borderWidth:1,borderColor:colors.border,borderRadius:9,backgroundColor:'#fff',padding:13},debtLate:{borderColor:'#e28c8c',backgroundColor:'#fff4f4'},debtPaid:{backgroundColor:'#f3faf5'},debtTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},month:{color:colors.ink,fontSize: 18,fontWeight:'900'},status:{color:colors.primaryDark,fontWeight:'900',backgroundColor:colors.softBlue,paddingHorizontal:9,paddingVertical:4,borderRadius:10,overflow:'hidden'},statusLate:{color:'#fff',backgroundColor:colors.red},statusPaid:{color:colors.green,backgroundColor:colors.softGreen},grid:{flexDirection:'row',flexWrap:'wrap',gap:18,marginTop:12},cellLabel:{color:colors.muted,fontSize: 14,fontWeight:'800'},cellValue:{color:colors.ink,fontWeight:'800',marginTop:3},totalValue:{color:colors.red,fontWeight:'900',marginTop:3}});
