import React from 'react';
import {Linking,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {colors,shadow} from '../ui/theme';

const privacy=[
  ['1. Objetivo','Esta Política explica como o Lar em Dia trata dados pessoais no site, no aplicativo e na plataforma de gestão condominial.'],
  ['2. Dados tratados','Podemos tratar dados de identificação e contato, vínculo com condomínio e unidade, dados de acesso, comunicações, reservas, enquetes, ocorrências, cobranças, pagamentos e documentos inseridos conforme as funcionalidades utilizadas.'],
  ['3. Finalidades','Os dados são usados para autenticar usuários, prestar as funcionalidades contratadas, manter segurança e auditoria, enviar comunicações solicitadas, atender suporte, cumprir obrigações legais e responder pedidos de proposta.'],
  ['4. Compartilhamento','Os dados podem ser processados por fornecedores necessários à operação, como hospedagem, banco de dados, e-mail, notificações e serviços bancários, sempre limitados à finalidade aplicável. Também poderão ser compartilhados quando houver obrigação legal.'],
  ['5. Armazenamento e segurança','Adotamos controles de acesso, autenticação, registros de auditoria e medidas técnicas compatíveis com a natureza do serviço. Os dados são mantidos pelo período necessário à prestação, ao cumprimento de obrigações e ao exercício regular de direitos.'],
  ['6. Direitos do titular','O titular pode solicitar confirmação de tratamento, acesso, correção, informação sobre compartilhamento, anonimização, bloqueio ou eliminação quando aplicável, portabilidade e revisão ou revogação de consentimento nos casos previstos na LGPD.'],
  ['7. Responsabilidades do condomínio','O condomínio contratante define e administra parte dos dados de moradores dentro da plataforma. Solicitações relacionadas a cadastros e rotinas condominiais podem exigir participação do síndico ou responsável pelo condomínio.'],
  ['8. Contato','Para dúvidas ou exercício de direitos relacionados a dados pessoais, escreva para laremdia.condominio@gmail.com. Poderemos solicitar informações para confirmar a identidade do solicitante.'],
  ['9. Atualizações','Esta Política poderá ser atualizada para refletir mudanças legais, técnicas ou no serviço. A versão vigente ficará disponível nesta página.'],
];
const terms=[
  ['1. Aceitação','Ao acessar ou utilizar o Lar em Dia, o usuário declara ter lido e aceito estes Termos e as regras definidas pelo condomínio responsável por seu cadastro.'],
  ['2. Serviço','O Lar em Dia oferece recursos de gestão condominial, incluindo cadastros, cobranças, prestação de contas, comunicação, ocorrências, enquetes, reservas e outras funcionalidades habilitadas no plano do condomínio.'],
  ['3. Conta e acesso','Cada usuário deve utilizar suas próprias credenciais, manter a senha protegida e informar imediatamente suspeitas de acesso indevido. As ações realizadas com a conta ficam registradas conforme os controles de segurança e auditoria.'],
  ['4. Uso adequado','É proibido usar a plataforma para prática ilícita, violação de direitos, tentativa de acesso não autorizado, envio de conteúdo malicioso ou interferência no funcionamento do serviço.'],
  ['5. Conteúdo e dados','O condomínio e seus usuários são responsáveis pela legitimidade, exatidão e finalidade dos dados e documentos inseridos. O Lar em Dia processa essas informações para disponibilizar o serviço contratado.'],
  ['6. Cobranças e serviços de terceiros','Boletos, Pix, notificações, e-mails e outros recursos podem depender de instituições e provedores externos. Prazos, disponibilidade e regras desses serviços também podem afetar a operação.'],
  ['7. Disponibilidade e manutenção','A plataforma poderá passar por atualizações, manutenções ou interrupções necessárias. Buscamos preservar a continuidade e informar ocorrências relevantes pelos canais disponíveis.'],
  ['8. Suspensão','Contas ou acessos poderão ser suspensos em caso de risco à segurança, uso indevido, solicitação do condomínio, encerramento contratual ou obrigação legal.'],
  ['9. Privacidade','O tratamento de dados pessoais segue a Política de Privacidade disponível na plataforma e a legislação aplicável, incluindo a Lei Geral de Proteção de Dados Pessoais.'],
  ['10. Contato','Dúvidas sobre estes Termos podem ser enviadas para laremdia.condominio@gmail.com.'],
];

export default function LegalDocument({route,navigation}:any){const isPrivacy=route.params?.document==='privacy',sections=isPrivacy?privacy:terms;return <ScrollView contentContainerStyle={styles.page}><View style={styles.top}><Pressable onPress={()=>navigation.goBack()} style={styles.back}><Text style={styles.backText}>‹ Voltar</Text></Pressable><Text style={styles.brand}>LAR EM DIA</Text></View><View style={styles.card}><Text style={styles.eyebrow}>DOCUMENTO LEGAL</Text><Text style={styles.title}>{isPrivacy?'Política de Privacidade':'Termos de Uso'}</Text><Text style={styles.updated}>Última atualização: 4 de agosto de 2026</Text>{sections.map(([title,text])=><View key={title} style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.body}>{text}</Text></View>)}<Pressable onPress={()=>Linking.openURL('mailto:laremdia.condominio@gmail.com')} style={styles.contact}><Text style={styles.contactLabel}>Fale com o Lar em Dia</Text><Text style={styles.contactEmail}>laremdia.condominio@gmail.com</Text></Pressable></View></ScrollView>}
const styles=StyleSheet.create({page:{backgroundColor:'#f5f7fb',padding:20,paddingBottom:60},top:{width:'100%',maxWidth:900,alignSelf:'center',flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},back:{paddingVertical:10,paddingRight:16},backText:{color:colors.primary,fontSize:15,fontWeight:'900'},brand:{color:colors.navy,fontWeight:'900',letterSpacing:1},card:{width:'100%',maxWidth:900,alignSelf:'center',backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:colors.border,padding:28,...shadow},eyebrow:{color:colors.primary,fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.ink,fontSize:29,fontWeight:'900',marginTop:7},updated:{color:colors.muted,fontSize:13,marginTop:7,marginBottom:16},section:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:17,marginTop:17},sectionTitle:{color:colors.ink,fontSize:17,fontWeight:'900'},body:{color:'#475467',fontSize:15,lineHeight:23,marginTop:7},contact:{marginTop:26,backgroundColor:colors.softBlue,borderRadius:12,padding:17},contactLabel:{color:colors.primaryDark,fontSize:13,fontWeight:'800'},contactEmail:{color:colors.primary,fontSize:16,fontWeight:'900',marginTop:4}});
