import React, { useCallback, useContext, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiRequest } from '../api/client';
import { AuthContext } from '../context/AuthContext';
import { AppButton, AppDialog, EmptyState, Panel } from '../ui/components';
import { colors, layout } from '../ui/theme';
import { useBreakpoint } from '../ui/responsive';
import FeatureTour, { type TourStep } from '../ui/FeatureTour';
import { useSectionTour } from '../ui/useSectionTour';

type Option = { id:string; label:string; position:number; vote_count:number|null };
type Poll = { id:string; title:string; description:string|null; status:'draft'|'open'|'closed'|'canceled'; closes_at:string|null; created_at:string; created_by_name:string; vote_count:number; selected_option_id:string|null; options:Option[] };
const statusLabel = { draft:'Rascunho', open:'Aberta', closed:'Encerrada', canceled:'Cancelada' };
const formatDate = (value:string) => new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const parseBrazilianDateTime = (value:string): Date | null => {
  const match = value.trim().match(/^(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2}):(\d{2})$/);
  if (!match) return null;
  const [,day,month,year,hour,minute] = match.map(Number);
  const parsed = new Date(year,month-1,day,hour,minute,0,0);
  if (parsed.getFullYear()!==year || parsed.getMonth()!==month-1 || parsed.getDate()!==day || parsed.getHours()!==hour || parsed.getMinutes()!==minute) return null;
  return parsed;
};

export default function Polls() {
  const { isDesktop } = useBreakpoint();
  const { user,userToken } = useContext(AuthContext);
  const manager = user?.role==='sindico'||user?.role==='subsindico';
  const {scrollRef,tourOpen,registerSection,scrollToSection,openTour,closeTour,isActive}=useSectionTour();
  const [polls,setPolls]=useState<Poll[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [closesAt,setClosesAt]=useState(''); const [options,setOptions]=useState(['','']);
  const [busy,setBusy]=useState<string|null>(null); const [dialog,setDialog]=useState({visible:false,title:'',message:'',tone:'info' as 'info'|'success'|'error'});
  const show=(title:string,message:string,tone:'info'|'success'|'error'='info')=>setDialog({visible:true,title,message,tone});
  const load=useCallback(async(silent=false)=>{if(!userToken)return;if(!silent)setLoading(true);try{const data=await apiRequest<{polls:Poll[]}>('/polls',userToken);setPolls(data.polls);}catch(e){if(!silent)show('Não foi possível carregar',e instanceof Error?e.message:'Tente novamente.','error');}finally{setLoading(false);setRefreshing(false);}},[userToken]);
  useEffect(()=>{load();},[load]);
  const create=async()=>{if(!userToken)return;setBusy('create');try{const parsed=closesAt.trim()?parseBrazilianDateTime(closesAt):null;if(closesAt.trim()&&!parsed)throw new Error('Use uma data válida no formato DD/MM/AAAA HH:mm.');await apiRequest('/polls',userToken,{method:'POST',body:JSON.stringify({title,description,options,closesAt:parsed?.toISOString()})});setTitle('');setDescription('');setClosesAt('');setOptions(['','']);await load(true);show('Rascunho criado','Revise a enquete e publique quando estiver pronta.','success');}catch(e){show('Enquete não criada',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
  const action=async(poll:Poll,kind:'publish'|'close')=>{if(!userToken)return;setBusy(poll.id);try{await apiRequest(`/polls/${poll.id}/${kind}`,userToken,{method:'PATCH'});await load(true);show(kind==='publish'?'Enquete publicada':'Enquete encerrada',kind==='publish'?'Os moradores ativos foram avisados.':'Os resultados finais já estão disponíveis.','success');}catch(e){show('Operação não concluída',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
  const vote=async(poll:Poll,optionId:string)=>{if(!userToken)return;setBusy(poll.id);try{await apiRequest(`/polls/${poll.id}/vote`,userToken,{method:'POST',body:JSON.stringify({optionId})});await load(true);show('Resposta registrada','Seu voto foi salvo. O resultado aparecerá após o encerramento.','success');}catch(e){show('Voto não registrado',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
  const managerTourSteps:TourStep[]=[
    {key:'create',title:'Criar nova enquete',description:'O título deve ter de 3 a 160 caracteres e a descrição (opcional) no máximo 2.000. Informe de 2 a 10 opções, sem repetir texto entre elas. O encerramento é opcional e precisa estar no formato DD/MM/AAAA HH:mm, sempre no futuro — sem prazo definido, você mesmo encerra manualmente quando quiser. A enquete nasce como rascunho e só fica visível pros moradores depois de publicada.'},
    {key:'list',title:'Enquetes do condomínio',description:'Rascunhos só aparecem pra você. Toque em "Publicar enquete" pra abrir a votação — todos os moradores (proprietários e inquilinos) com unidade ativa recebem uma notificação na hora. Como síndico/subsíndico você já vê os votos de cada opção mesmo com a enquete ainda aberta; os moradores só veem o resultado depois do encerramento. "Encerrar e divulgar resultado" fecha a votação em definitivo e libera o resultado final pra todo mundo.'},
  ];
  const residentTourSteps:TourStep[]=[
    {key:'list',title:'Disponíveis para você',description:'Enquetes abertas mostram as opções pra você votar — toque numa opção pra responder; o voto é único e não dá pra trocar depois. Enquanto a enquete estiver aberta você não vê o placar parcial (isso só fica visível pro síndico/subsíndico); depois que ela for encerrada, os votos de cada opção e o percentual aparecem aqui pra todo mundo.'},
  ];
  const tourSteps=manager?managerTourSteps:residentTourSteps;
  return <><ScrollView ref={scrollRef} contentContainerStyle={[styles.content,isDesktop&&styles.desktop]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true);}}/>} keyboardShouldPersistTaps="handled">
    <View style={styles.headerRow}><View style={styles.grow}><Text style={styles.eyebrow}>PARTICIPAÇÃO DO CONDOMÍNIO</Text><Text style={styles.pageTitle}>Enquetes</Text><Text style={styles.subtitle}>Consulte os moradores e acompanhe as respostas.</Text></View><Pressable onPress={openTour} style={styles.tourButton}><Text style={styles.tourButtonText}>? Tour desta tela</Text></Pressable></View>
    {manager?<View ref={registerSection('create')} style={[isActive('create')&&styles.tourHighlight]}><Panel><Text style={styles.panelTitle}>Criar nova enquete</Text><Text style={styles.label}>Título</Text><TextInput style={styles.input} value={title} onChangeText={setTitle} maxLength={160} placeholder="Ex.: Horário da próxima assembleia"/><Text style={styles.label}>Descrição (opcional)</Text><TextInput style={[styles.input,styles.multiline]} value={description} onChangeText={setDescription} multiline maxLength={2000}/><Text style={styles.label}>Encerramento (opcional)</Text><TextInput style={styles.input} value={closesAt} onChangeText={setClosesAt} placeholder="20/08/2026 18:00"/><Text style={styles.label}>Opções</Text>{options.map((option,index)=><View key={index} style={styles.optionEdit}><TextInput style={[styles.input,styles.grow]} value={option} onChangeText={value=>setOptions(current=>current.map((item,i)=>i===index?value:item))} placeholder={`Opção ${index+1}`}/>{options.length>2?<Pressable onPress={()=>setOptions(current=>current.filter((_,i)=>i!==index))}><Text style={styles.remove}>Remover</Text></Pressable>:null}</View>)}{options.length<10?<Pressable onPress={()=>setOptions(current=>[...current,''])}><Text style={styles.add}>+ Adicionar opção</Text></Pressable>:null}<View style={styles.button}><AppButton title="Salvar rascunho" loading={busy==='create'} onPress={create}/></View></Panel></View>:null}
    <View ref={registerSection('list')} style={[isActive('list')&&styles.tourHighlight]}>
    <Text style={styles.sectionTitle}>{manager?'Enquetes do condomínio':'Disponíveis para você'}</Text>
    {loading?<ActivityIndicator size="large" color={colors.primary}/>:polls.length===0?<EmptyState title="Nenhuma enquete" description={manager?'Crie a primeira consulta aos moradores.':'As enquetes publicadas aparecerão aqui.'}/>:polls.map(poll=>{const resultsVisible=manager||poll.status==='closed'||poll.status==='canceled';return <View key={poll.id} style={styles.card}><View style={styles.top}><View style={styles.grow}><Text style={styles.pollTitle}>{poll.title}</Text><Text style={styles.meta}>{statusLabel[poll.status]} · criada por {poll.created_by_name}</Text></View><Text style={[styles.badge,poll.status==='open'&&styles.open]}>{statusLabel[poll.status]}</Text></View>{poll.description?<Text style={styles.description}>{poll.description}</Text>:null}{poll.closes_at?<Text style={styles.deadline}>Prazo: {formatDate(poll.closes_at)}</Text>:null}<View style={styles.options}>{poll.options.map(option=>{const percentage=poll.vote_count?Math.round(((option.vote_count||0)/poll.vote_count)*100):0;return <Pressable key={option.id} disabled={manager||poll.status!=='open'||!!poll.selected_option_id||busy===poll.id} onPress={()=>vote(poll,option.id)} style={[styles.choice,poll.selected_option_id===option.id&&styles.selected]}><Text style={styles.choiceText}>{option.label}</Text>{resultsVisible?<Text style={styles.result}>{option.vote_count||0} voto(s) · {percentage}%</Text>:poll.selected_option_id===option.id?<Text style={styles.voted}>Sua resposta</Text>:null}</Pressable>})}</View>{resultsVisible?<Text style={styles.total}>{poll.vote_count} resposta(s)</Text>:null}{manager&&poll.status==='draft'?<View style={styles.action}><AppButton title="Publicar enquete" loading={busy===poll.id} onPress={()=>action(poll,'publish')}/></View>:null}{manager&&poll.status==='open'?<View style={styles.action}><AppButton title="Encerrar e divulgar resultado" variant="secondary" loading={busy===poll.id} onPress={()=>action(poll,'close')}/></View>:null}</View>})}
    </View>
  </ScrollView><AppDialog {...dialog} onClose={()=>setDialog(current=>({...current,visible:false}))}/><FeatureTour steps={tourSteps} visible={tourOpen} onClose={closeTour} onStepChange={step=>scrollToSection(step.key)}/></>;
}

const styles=StyleSheet.create({content:{width:'100%',alignSelf:'center',padding:28,gap:18,paddingBottom:70},desktop:{maxWidth:900},headerRow:{flexDirection:'row',alignItems:'flex-start',gap:12,flexWrap:'wrap'},tourButton:{borderWidth:1,borderColor:colors.primary,borderRadius:20,paddingHorizontal:14,paddingVertical:9,backgroundColor:colors.softBlue},tourButtonText:{color:colors.primaryDark,fontWeight:'900',fontSize:13},tourHighlight:{borderWidth:2,borderColor:colors.primary,borderRadius:16,padding:6,margin:-6},eyebrow:{color:colors.primary,fontSize:14,fontWeight:'900',letterSpacing:1},pageTitle:{color:colors.ink,fontSize:27,fontWeight:'900',marginTop:5},subtitle:{color:colors.muted,fontSize:16,marginTop:5},panelTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},label:{color:colors.ink,fontSize:14,fontWeight:'800',marginTop:12,marginBottom:6},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:8,backgroundColor:'#fff',paddingHorizontal:12,color:colors.ink,fontSize:16},multiline:{minHeight:90,paddingTop:12,textAlignVertical:'top'},optionEdit:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:8},grow:{flex:1},remove:{color:colors.red,fontWeight:'800'},add:{color:colors.primary,fontWeight:'900',paddingVertical:10},button:{alignSelf:'flex-end',minWidth:190,marginTop:8},sectionTitle:{color:colors.ink,fontSize:20,fontWeight:'900'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:layout.radius,padding:18},top:{flexDirection:'row',gap:12,alignItems:'flex-start'},pollTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},meta:{color:colors.muted,fontSize:13,marginTop:4},badge:{color:colors.muted,backgroundColor:'#eef1f5',paddingHorizontal:9,paddingVertical:5,borderRadius:9,fontSize:12,fontWeight:'900'},open:{color:colors.green,backgroundColor:colors.softGreen},description:{color:'#445466',fontSize:15,lineHeight:22,marginTop:13},deadline:{color:colors.muted,fontSize:13,fontWeight:'700',marginTop:8},options:{gap:9,marginTop:16},choice:{borderWidth:1,borderColor:colors.border,borderRadius:10,padding:13,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},selected:{borderColor:colors.primary,backgroundColor:colors.softBlue},choiceText:{color:colors.ink,fontSize:15,fontWeight:'800',flex:1},result:{color:colors.primaryDark,fontSize:13,fontWeight:'900'},voted:{color:colors.green,fontSize:13,fontWeight:'900'},total:{color:colors.muted,fontSize:13,fontWeight:'800',marginTop:12},action:{alignSelf:'flex-end',minWidth:210,marginTop:15}});
