import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,StyleSheet,Text,View} from 'react-native';
import {apiRequest} from '../api/client';
import {colors} from '../ui/theme';

type Occupied={id:string;starts_at:string;ends_at:string;status:'pending'|'approved'|'blocked';kind:'reservation'|'block';reason:string|null};
type Props={spaceId:string;spaceName:string;availableFrom:string;availableUntil:string;token:string;canRequest:boolean;refreshKey:string;onSelectSlot:(start:Date,end:Date)=>void};
const WEEK=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const pad=(value:number)=>String(value).padStart(2,'0');
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
const overlaps=(start:Date,end:Date,item:Occupied)=>start<new Date(item.ends_at)&&end>new Date(item.starts_at);

export default function ReservationCalendar({spaceId,spaceName,availableFrom,availableUntil,token,canRequest,refreshKey,onSelectSlot}:Props){
  const today=useMemo(()=>{const value=new Date();value.setHours(0,0,0,0);return value;},[]);
  const [month,setMonth]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1));
  const [selected,setSelected]=useState(today);const [occupied,setOccupied]=useState<Occupied[]>([]);const [loading,setLoading]=useState(false);const [removing,setRemoving]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!spaceId)return;setLoading(true);const from=new Date(month.getFullYear(),month.getMonth(),1),to=new Date(month.getFullYear(),month.getMonth()+1,1);try{const data=await apiRequest<{occupied:Occupied[]}>(`/space-reservations/availability?spaceId=${encodeURIComponent(spaceId)}&from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`,token);setOccupied(data.occupied);}catch{setOccupied([]);}finally{setLoading(false);}},[month,spaceId,token,refreshKey]);
  useEffect(()=>{load();},[load]);
  const firstOffset=new Date(month.getFullYear(),month.getMonth(),1).getDay(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
  const cells=Array.from({length:firstOffset+days},(_,index)=>index<firstOffset?null:new Date(month.getFullYear(),month.getMonth(),index-firstOffset+1));
  while(cells.length%7)cells.push(null);
  const firstHour=Number(availableFrom.slice(0,2)),lastHour=Number(availableUntil.slice(0,2));
  const slots=Array.from({length:Math.max(0,lastHour-firstHour)},(_,index)=>{const start=new Date(selected);start.setHours(firstHour+index,0,0,0);const end=new Date(start);end.setHours(start.getHours()+1);return{start,end,busy:occupied.some(item=>overlaps(start,end,item))};});
  const dayState=(day:Date)=>{const relevant=slotsFor(day).filter(slot=>slot.end>new Date());const busy=relevant.filter(slot=>occupied.some(item=>overlaps(slot.start,slot.end,item))).length;return !relevant.length?'past':busy===0?'free':busy===relevant.length?'busy':'partial';};
  const slotsFor=(day:Date)=>Array.from({length:Math.max(0,lastHour-firstHour)},(_,index)=>{const start=new Date(day);start.setHours(firstHour+index,0,0,0);const end=new Date(start);end.setHours(start.getHours()+1);return{start,end};});
  const selectedBookings=occupied.filter(item=>sameDay(new Date(item.starts_at),selected)||sameDay(new Date(item.ends_at),selected));
  const removeBlock=async(id:string)=>{setRemoving(id);try{await apiRequest(`/space-reservations/blocks/${id}`,token,{method:'DELETE'});await load();}finally{setRemoving(null);}};
  const changeMonth=(offset:number)=>{const next=new Date(month.getFullYear(),month.getMonth()+offset,1);setMonth(next);setSelected(next<today?today:next);};
  return <View style={styles.card}><View style={styles.spaceHeader}><Text style={styles.spaceName}>{spaceName}</Text><Text style={styles.hours}>Reservas das {availableFrom.slice(0,5)} às {availableUntil.slice(0,5)}</Text></View><View style={styles.header}><Pressable onPress={()=>changeMonth(-1)} style={styles.nav}><Text style={styles.navText}>‹</Text></Pressable><View><Text style={styles.title}>Calendário de disponibilidade</Text><Text style={styles.month}>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</Text></View><Pressable onPress={()=>changeMonth(1)} style={styles.nav}><Text style={styles.navText}>›</Text></Pressable></View>
  <View style={styles.legend}><Text style={styles.freeText}>● Livre</Text><Text style={styles.partialText}>● Parcial</Text><Text style={styles.busyText}>● Ocupado</Text></View>
  {loading?<ActivityIndicator color={colors.primary}/>:<><View style={styles.week}>{WEEK.map(day=><Text key={day} style={styles.weekText}>{day}</Text>)}</View><View style={styles.calendar}>{cells.map((day,index)=>day?<Pressable key={day.toISOString()} onPress={()=>setSelected(day)} style={[styles.day,sameDay(day,selected)&&styles.daySelected,dayState(day)==='past'&&styles.dayPast]}><Text style={[styles.dayNumber,sameDay(day,selected)&&styles.dayNumberSelected]}>{day.getDate()}</Text><View style={[styles.dot,dayState(day)==='free'&&styles.dotFree,dayState(day)==='partial'&&styles.dotPartial,dayState(day)==='busy'&&styles.dotBusy]}/></Pressable>:<View key={`empty-${index}`} style={styles.day}/>)}</View></>}
  <Text style={styles.selectedTitle}>{selected.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</Text>{selectedBookings.length?<View style={styles.bookings}>{selectedBookings.map((item,index)=><View key={`${item.starts_at}-${index}`} style={[styles.bookingCard,item.kind==='block'&&styles.blockCard]}><Text style={[styles.booking,item.kind==='block'&&styles.blockText]}>{item.kind==='block'?'Bloqueio administrativo':'Reserva'} · {new Date(item.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}–{new Date(item.ends_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</Text>{item.reason?<Text style={styles.reason}>{item.reason}</Text>:null}{item.kind==='block'&&!canRequest?<Pressable disabled={removing===item.id} onPress={()=>removeBlock(item.id)}><Text style={styles.removeBlock}>{removing===item.id?'Removendo...':'Remover bloqueio'}</Text></Pressable>:null}</View>)}</View>:<Text style={styles.noBookings}>Agenda totalmente livre neste dia.</Text>}
  <View style={styles.slots}>{slots.map(slot=>{const past=slot.end<=new Date(),disabled=slot.busy||past||!canRequest;return <Pressable key={slot.start.toISOString()} disabled={disabled} onPress={()=>onSelectSlot(slot.start,slot.end)} style={[styles.slot,slot.busy&&styles.slotBusy,past&&styles.slotPast]}><Text style={[styles.slotText,slot.busy&&styles.slotBusyText]}>{pad(slot.start.getHours())}:00</Text><Text style={[styles.slotStatus,slot.busy&&styles.slotBusyText]}>{slot.busy?'Ocupado':past?'Encerrado':canRequest?'Selecionar':'Livre'}</Text></Pressable>})}</View></View>;
}
const styles=StyleSheet.create({card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:18,padding:20,gap:15},spaceHeader:{backgroundColor:colors.navy,borderRadius:13,padding:15},spaceName:{color:'#fff',fontSize:20,fontWeight:'900'},hours:{color:'#cfe1f7',fontSize:13,fontWeight:'800',marginTop:4},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},title:{color:colors.ink,fontSize:18,fontWeight:'900',textAlign:'center'},month:{color:colors.muted,fontSize:14,textAlign:'center',marginTop:3,textTransform:'capitalize'},nav:{width:44,height:44,borderRadius:22,backgroundColor:colors.softBlue,alignItems:'center',justifyContent:'center'},navText:{color:colors.primary,fontSize:28,fontWeight:'800',lineHeight:30},legend:{flexDirection:'row',justifyContent:'center',flexWrap:'wrap',gap:14,backgroundColor:'#f8fafc',padding:10,borderRadius:10},freeText:{color:colors.green,fontWeight:'800'},partialText:{color:colors.amber,fontWeight:'800'},busyText:{color:colors.red,fontWeight:'800'},week:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:colors.border,paddingBottom:6},weekText:{width:'14.285%',textAlign:'center',color:colors.muted,fontSize:12,fontWeight:'800'},calendar:{flexDirection:'row',flexWrap:'wrap'},day:{width:'14.285%',minHeight:60,alignItems:'center',justifyContent:'center',borderRadius:11},daySelected:{backgroundColor:colors.primary},dayPast:{opacity:.38},dayNumber:{color:colors.ink,fontSize:15,fontWeight:'800'},dayNumberSelected:{color:'#fff'},dot:{width:7,height:7,borderRadius:4,marginTop:6,backgroundColor:'#cbd5e1'},dotFree:{backgroundColor:colors.green},dotPartial:{backgroundColor:colors.amber},dotBusy:{backgroundColor:colors.red},selectedTitle:{color:colors.ink,fontSize:17,fontWeight:'900',textTransform:'capitalize',borderTopWidth:1,borderTopColor:colors.border,paddingTop:14},bookings:{gap:7},bookingCard:{borderLeftWidth:4,borderLeftColor:colors.red,backgroundColor:'#fff7f7',borderRadius:8,padding:9},blockCard:{borderLeftColor:colors.lilac,backgroundColor:'#f5f0ff'},booking:{color:colors.red,fontSize:13,fontWeight:'800'},blockText:{color:colors.lilac},reason:{color:colors.muted,fontSize:12,marginTop:3},removeBlock:{color:colors.red,fontSize:12,fontWeight:'900',marginTop:8,textDecorationLine:'underline'},noBookings:{color:colors.green,fontSize:13,fontWeight:'800'},slots:{flexDirection:'row',flexWrap:'wrap',gap:8},slot:{minWidth:104,flexGrow:1,borderWidth:1,borderColor:'#a9ddcf',backgroundColor:colors.softGreen,borderRadius:10,padding:10},slotBusy:{borderColor:'#efb4b4',backgroundColor:'#fff0f0'},slotPast:{opacity:.4},slotText:{color:colors.ink,fontWeight:'900'},slotStatus:{color:colors.green,fontSize:11,fontWeight:'800',marginTop:2},slotBusyText:{color:colors.red}});
