import React,{useCallback,useContext,useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {apiRequest} from '../api/client';import {AuthContext} from '../context/AuthContext';import {AppButton,AppDialog,EmptyState,Panel} from '../ui/components';import {colors,layout} from '../ui/theme';import {useBreakpoint} from '../ui/responsive';
import ReservationCalendar from './ReservationCalendar';
import FeatureTour, {type TourStep} from '../ui/FeatureTour';
import {useSectionTour} from '../ui/useSectionTour';
type Space={id:string;name:string;description:string|null;rules:string|null;capacity:number|null;available_from:string;available_until:string;active:boolean};
type Reservation={id:string;space_id:string;space_name:string;requested_by_name:string;unit_label:string|null;starts_at:string;ends_at:string;purpose:string|null;status:'pending'|'approved'|'rejected'|'canceled';review_note:string|null};
const labels={pending:'Aguardando aprovação',approved:'Aprovada',rejected:'Rejeitada',canceled:'Cancelada'};
const parse=(value:string)=>{const m=value.trim().match(/^(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2}):(\d{2})$/);if(!m)return null;const [,d,mo,y,h,mi]=m.map(Number),date=new Date(y,mo-1,d,h,mi);return date.getFullYear()===y&&date.getMonth()===mo-1&&date.getDate()===d&&date.getHours()===h&&date.getMinutes()===mi?date:null;};
const parseDay=(value:string)=>{const m=value.trim().match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return null;const [,d,mo,y]=m.map(Number),date=new Date(y,mo-1,d,0,0,0,0);return date.getFullYear()===y&&date.getMonth()===mo-1&&date.getDate()===d?date:null;};
const dt=(value:string)=>new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
export default function SpaceReservations(){const {isDesktop}=useBreakpoint();const {user,userToken}=useContext(AuthContext);const manager=user?.role==='sindico'||user?.role==='subsindico';const [spaces,setSpaces]=useState<Space[]>([]),[reservations,setReservations]=useState<Reservation[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState<string|null>(null);const [name,setName]=useState(''),[description,setDescription]=useState(''),[rules,setRules]=useState(''),[capacity,setCapacity]=useState(''),[availableFrom,setAvailableFrom]=useState('08:00'),[availableUntil,setAvailableUntil]=useState('23:00');const [spaceId,setSpaceId]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[purpose,setPurpose]=useState('');const [scheduleFrom,setScheduleFrom]=useState('08:00'),[scheduleUntil,setScheduleUntil]=useState('23:00'),[blockDay,setBlockDay]=useState(''),[blockReason,setBlockReason]=useState('');const [rejectionNotes,setRejectionNotes]=useState<Record<string,string>>({});
const {scrollRef,tourOpen,registerSection,scrollToSection,openTour,closeTour,isActive}=useSectionTour();
const managerTourSteps:TourStep[]=[
  {key:'spaces',title:'Espaços disponíveis',description:'Cada card é um espaço cadastrado (salão de festas, quadra, churrasqueira etc.). Toque num espaço pra selecioná-lo — os painéis abaixo (calendário, horário permitido, bloqueio) sempre agem sobre o espaço selecionado no momento.'},
  {key:'createSpace',title:'Cadastrar espaço',description:'Nome, descrição e regras de uso são só informativos pros moradores. Capacidade é opcional. "Reservas a partir de/até" define o horário diário permitido logo na criação — dá pra ajustar depois no painel "Horário diário permitido".'},
  {key:'calendar',title:'Calendário do espaço',description:'O ponto colorido em cada dia mostra a situação: verde = livre, amarelo = parcialmente ocupado, vermelho = totalmente ocupado. Toque num dia pra ver os horários e reservas/bloqueios daquele dia embaixo do calendário.'},
  {key:'schedule',title:'Horário diário permitido',description:'Regra permanente do espaço: fora desse intervalo, nenhum morador consegue solicitar reserva, nem no calendário nem digitando manualmente. Use pra limitar o funcionamento diário (ex.: piscina só das 08h às 21h).'},
  {key:'block',title:'Bloquear um dia inteiro',description:'Pra manutenção, evento interno ou qualquer indisponibilidade excepcional. Bloqueia o dia inteiro (não só um horário) e exige um motivo — esse motivo fica registrado na Auditoria. Não é possível bloquear um dia que já tem reserva pendente ou aprovada: cancele antes.'},
  {key:'requests',title:'Solicitações',description:'Pedidos dos moradores aparecem aqui como "Aguardando aprovação". Pra rejeitar, é obrigatório escrever uma justificativa (o morador recebe essa mensagem). Aprovar ou rejeitar dispara uma notificação automática pro morador.'},
];
const residentTourSteps:TourStep[]=[
  {key:'spaces',title:'Espaços disponíveis',description:'Veja os espaços que o condomínio disponibiliza pra reserva, com descrição, regras de uso e capacidade (quando informada). Espaços marcados como "Indisponível" não podem ser selecionados no momento.'},
  {key:'calendar',title:'Calendário do espaço',description:'O ponto colorido em cada dia mostra livre (verde), parcialmente ocupado (amarelo) ou totalmente ocupado (vermelho). Toque num dia pra ver os horários disponíveis embaixo — só aparecem os horários dentro do funcionamento diário daquele espaço.'},
  {key:'calendar',title:'Selecionar um horário',description:'Toque num horário livre no calendário pra preencher automaticamente os campos de início e término da solicitação — ou digite manualmente no formato DD/MM/AAAA HH:mm, se preferir.'},
  {key:'requestForm',title:'Solicitar reserva',description:'A reserva não é confirmada na hora: fica "Aguardando aprovação" até o síndico ou subsíndico analisar. Você recebe uma notificação assim que ela for aprovada ou rejeitada (com o motivo, se rejeitada).'},
  {key:'requests',title:'Minhas reservas',description:'Acompanhe o status de cada solicitação sua. Enquanto estiver "Aguardando aprovação" ou "Aprovada", você pode cancelar por conta própria — depois de cancelada ou rejeitada, não dá mais pra reverter por aqui.'},
];
const tourSteps=manager?managerTourSteps:residentTourSteps;
// Bloqueios (space_schedule_blocks) não fazem parte de `reservations` — sem
// isso, criar um bloqueio não muda o refreshKey do calendário e ele só
// aparece depois de um refresh manual da tela.
const [blocksVersion,setBlocksVersion]=useState(0);const [dialog,setDialog]=useState({visible:false,title:'',message:'',tone:'info' as 'info'|'success'|'error'});const show=(title:string,message:string,tone:'info'|'success'|'error'='info')=>setDialog({visible:true,title,message,tone});
const load=useCallback(async(silent=false)=>{if(!userToken)return;if(!silent)setLoading(true);try{const data=await apiRequest<{spaces:Space[];reservations:Reservation[]}>('/space-reservations',userToken);setSpaces(data.spaces);setReservations(data.reservations);if(!spaceId&&data.spaces[0])setSpaceId(data.spaces[0].id);}catch(e){if(!silent)show('Não foi possível carregar',e instanceof Error?e.message:'Tente novamente.','error');}finally{setLoading(false);setRefreshing(false);}},[userToken,spaceId]);useEffect(()=>{load();},[load]);
useEffect(()=>{const selected=spaces.find(item=>item.id===spaceId);if(selected){setScheduleFrom(selected.available_from.slice(0,5));setScheduleUntil(selected.available_until.slice(0,5));}},[spaceId,spaces]);
const createSpace=async()=>{if(!userToken)return;setBusy('space');try{await apiRequest('/space-reservations/spaces',userToken,{method:'POST',body:JSON.stringify({name,description,rules,capacity:capacity?Number(capacity):null,availableFrom,availableUntil})});setName('');setDescription('');setRules('');setCapacity('');await load(true);show('Espaço cadastrado','O espaço já está disponível para solicitações.','success');}catch(e){show('Espaço não cadastrado',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
const updateSchedule=async()=>{if(!userToken)return;setBusy('schedule');try{await apiRequest(`/space-reservations/spaces/${spaceId}/schedule`,userToken,{method:'PATCH',body:JSON.stringify({availableFrom:scheduleFrom,availableUntil:scheduleUntil})});await load(true);show('Horário atualizado',`O espaço poderá ser reservado diariamente entre ${scheduleFrom} e ${scheduleUntil}.`,'success');}catch(e){show('Horário não atualizado',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
const blockSchedule=async()=>{if(!userToken)return;const startsAt=parseDay(blockDay),endsAt=startsAt?new Date(startsAt):null;if(endsAt)endsAt.setDate(endsAt.getDate()+1);if(!startsAt||!endsAt){show('Data inválida','Use uma data no formato DD/MM/AAAA.','error');return;}setBusy('block');try{await apiRequest('/space-reservations/blocks',userToken,{method:'POST',body:JSON.stringify({spaceId,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),reason:blockReason})});setBlockDay('');setBlockReason('');setBlocksVersion(current=>current+1);await load(true);show('Agenda bloqueada','O dia inteiro foi bloqueado.','success');}catch(e){show('Bloqueio não criado',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
const request=async()=>{if(!userToken)return;const startsAt=parse(start),endsAt=parse(end);if(!startsAt||!endsAt){show('Período inválido','Use o formato DD/MM/AAAA HH:mm para início e término.','error');return;}setBusy('request');try{await apiRequest('/space-reservations/reservations',userToken,{method:'POST',body:JSON.stringify({spaceId,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),purpose})});setStart('');setEnd('');setPurpose('');await load(true);show('Solicitação enviada','A administração foi notificada para analisar sua reserva.','success');}catch(e){show('Reserva não solicitada',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
const act=async(item:Reservation,path:string,body?:unknown)=>{if(!userToken)return;setBusy(item.id);try{await apiRequest(`/space-reservations/reservations/${item.id}/${path}`,userToken,{method:'PATCH',body:body?JSON.stringify(body):undefined});await load(true);show('Reserva atualizada','A alteração foi registrada.','success');}catch(e){show('Não foi possível atualizar',e instanceof Error?e.message:'Tente novamente.','error');}finally{setBusy(null);}};
return <><ScrollView ref={scrollRef} contentContainerStyle={[styles.content,isDesktop&&styles.desktop]} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true);}}/>}><View style={styles.headerRow}><View style={styles.grow}><Text style={styles.eyebrow}>ÁREAS COMUNS</Text><Text style={styles.title}>Reserva de espaços</Text><Text style={styles.subtitle}>{manager?'Cadastre os espaços e analise as solicitações.':'Consulte os espaços e solicite uma reserva.'}</Text></View><Pressable onPress={openTour} style={styles.tourButton}><Text style={styles.tourButtonText}>? Tour desta tela</Text></Pressable></View>
{manager?<View ref={registerSection('createSpace')} style={[isActive('createSpace')&&styles.tourHighlight]}><Panel><Text style={styles.panelTitle}>Cadastrar espaço</Text><Text style={styles.label}>Nome</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Ex.: Salão de festas"/><Text style={styles.label}>Descrição</Text><TextInput style={[styles.input,styles.multi]} value={description} onChangeText={setDescription} multiline/><Text style={styles.label}>Regras de utilização</Text><TextInput style={[styles.input,styles.multi]} value={rules} onChangeText={setRules} multiline/><Text style={styles.label}>Capacidade (opcional)</Text><TextInput style={styles.input} value={capacity} onChangeText={setCapacity} keyboardType="number-pad"/><View style={styles.timeRow}><View style={styles.grow}><Text style={styles.label}>Reservas a partir de</Text><TextInput style={styles.input} value={availableFrom} onChangeText={setAvailableFrom} placeholder="08:00"/></View><View style={styles.grow}><Text style={styles.label}>Reservas até</Text><TextInput style={styles.input} value={availableUntil} onChangeText={setAvailableUntil} placeholder="23:00"/></View></View><View style={styles.button}><AppButton title="Cadastrar espaço" loading={busy==='space'} onPress={createSpace}/></View></Panel></View>:null}
<View ref={registerSection('spaces')} style={[isActive('spaces')&&styles.tourHighlight]}><Text style={styles.section}>Espaços disponíveis</Text>{loading?<ActivityIndicator size="large" color={colors.primary}/>:spaces.length===0?<EmptyState title="Nenhum espaço cadastrado" description="A administração ainda não disponibilizou áreas para reserva."/>:<View style={styles.grid}>{spaces.map(space=><Pressable key={space.id} disabled={!space.active} onPress={()=>setSpaceId(space.id)} style={[styles.space,spaceId===space.id&&styles.selected,!space.active&&styles.inactive]}><View style={styles.row}><Text style={styles.spaceName}>{space.name}</Text>{space.capacity?<Text style={styles.capacity}>Até {space.capacity} pessoas</Text>:null}</View>{space.description?<Text style={styles.text}>{space.description}</Text>:null}{space.rules?<Text style={styles.rules}>Regras: {space.rules}</Text>:null}{!space.active?<Text style={styles.disabled}>Indisponível</Text>:null}</Pressable>)}</View>}</View>
{spaceId&&userToken&&spaces.find(item=>item.id===spaceId)?<View ref={registerSection('calendar')} style={[isActive('calendar')&&styles.tourHighlight]}><ReservationCalendar spaceId={spaceId} spaceName={spaces.find(item=>item.id===spaceId)!.name} availableFrom={spaces.find(item=>item.id===spaceId)!.available_from} availableUntil={spaces.find(item=>item.id===spaceId)!.available_until} token={userToken} canRequest={!manager} refreshKey={reservations.map(item=>`${item.id}:${item.status}`).join('|')+'|'+blocksVersion} onSelectSlot={(slotStart,slotEnd)=>{const format=(value:Date)=>`${String(value.getDate()).padStart(2,'0')}/${String(value.getMonth()+1).padStart(2,'0')}/${value.getFullYear()} ${String(value.getHours()).padStart(2,'0')}:${String(value.getMinutes()).padStart(2,'0')}`;setStart(format(slotStart));setEnd(format(slotEnd));}}/></View>:null}
{manager&&spaceId?<><View ref={registerSection('schedule')} style={[isActive('schedule')&&styles.tourHighlight]}><Panel><Text style={styles.panelTitle}>Horário diário permitido</Text><Text style={styles.help}>Regra permanente para este espaço. Fora deste intervalo nenhum morador poderá reservar. Exemplo: piscina disponível diariamente das 08:00 às 21:00.</Text><View style={styles.timeRow}><View style={styles.grow}><Text style={styles.label}>Reservas a partir de</Text><TextInput style={styles.input} value={scheduleFrom} onChangeText={setScheduleFrom} placeholder="08:00"/></View><View style={styles.grow}><Text style={styles.label}>Reservas até</Text><TextInput style={styles.input} value={scheduleUntil} onChangeText={setScheduleUntil} placeholder="21:00"/></View></View><View style={styles.button}><AppButton title="Salvar horário diário" loading={busy==='schedule'} onPress={updateSchedule}/></View></Panel></View><View ref={registerSection('block')} style={[isActive('block')&&styles.tourHighlight]}><Panel><Text style={styles.panelTitle}>Bloquear um dia inteiro</Text><Text style={styles.help}>Use para manutenção, evento interno ou outra indisponibilidade excepcional.</Text><Text style={styles.label}>Dia do bloqueio</Text><TextInput style={styles.input} value={blockDay} onChangeText={setBlockDay} placeholder="05/08/2026"/><Text style={styles.label}>Motivo obrigatório</Text><TextInput style={[styles.input,styles.multi]} value={blockReason} onChangeText={setBlockReason} multiline maxLength={500} placeholder="Ex.: Manutenção preventiva"/><View style={styles.button}><AppButton title="Bloquear dia inteiro" variant="danger" loading={busy==='block'} onPress={blockSchedule}/></View></Panel></View></>:null}
{!manager&&spaces.length?<View ref={registerSection('requestForm')} style={[isActive('requestForm')&&styles.tourHighlight]}><Panel><Text style={styles.panelTitle}>Solicitar reserva</Text><Text style={styles.label}>Espaço</Text><View style={styles.chips}>{spaces.filter(s=>s.active).map(s=><Pressable key={s.id} onPress={()=>setSpaceId(s.id)} style={[styles.chip,spaceId===s.id&&styles.chipOn]}><Text style={[styles.chipText,spaceId===s.id&&styles.chipTextOn]}>{s.name}</Text></Pressable>)}</View><Text style={styles.label}>Início</Text><TextInput style={styles.input} value={start} onChangeText={setStart} placeholder="05/08/2026 17:00"/><Text style={styles.label}>Término</Text><TextInput style={styles.input} value={end} onChangeText={setEnd} placeholder="05/08/2026 22:00"/><Text style={styles.label}>Finalidade (opcional)</Text><TextInput style={[styles.input,styles.multi]} value={purpose} onChangeText={setPurpose} multiline/><View style={styles.button}><AppButton title="Solicitar reserva" loading={busy==='request'} disabled={!spaceId} onPress={request}/></View></Panel></View>:null}
<View ref={registerSection('requests')} style={[isActive('requests')&&styles.tourHighlight]}><Text style={styles.section}>{manager?'Solicitações':'Minhas reservas'}</Text>{!loading&&reservations.length===0?<EmptyState title="Nenhuma reserva" description={manager?'As solicitações dos moradores aparecerão aqui.':'Você ainda não solicitou uma reserva.'}/>:reservations.map(item=><View key={item.id} style={styles.reservation}><View style={styles.row}><View style={styles.grow}><Text style={styles.spaceName}>{item.space_name}</Text><Text style={styles.meta}>{dt(item.starts_at)} até {dt(item.ends_at)}</Text></View><Text style={[styles.badge,item.status==='approved'&&styles.approved,item.status==='rejected'&&styles.rejected]}>{labels[item.status]}</Text></View>{manager?<Text style={styles.text}>{item.requested_by_name}{item.unit_label?` · ${item.unit_label}`:''}</Text>:null}{item.purpose?<Text style={styles.text}>Finalidade: {item.purpose}</Text>:null}{item.review_note?<Text style={styles.rejectionReason}>Justificativa: {item.review_note}</Text>:null}{manager&&item.status==='pending'?<><Text style={styles.label}>Justificativa para eventual rejeição</Text><TextInput style={[styles.input,styles.rejectInput]} value={rejectionNotes[item.id]||''} onChangeText={value=>setRejectionNotes(current=>({...current,[item.id]:value}))} multiline maxLength={500} placeholder="Obrigatória ao rejeitar"/></>:null}<View style={styles.actions}>{manager&&item.status==='pending'?<><AppButton title="Aprovar" loading={busy===item.id} onPress={()=>act(item,'review',{status:'approved'})}/><AppButton title="Rejeitar com justificativa" variant="danger" disabled={busy===item.id||!(rejectionNotes[item.id]||'').trim()} onPress={()=>act(item,'review',{status:'rejected',note:(rejectionNotes[item.id]||'').trim()})}/></>:null}{item.status==='pending'||item.status==='approved'?<AppButton title="Cancelar" variant="secondary" disabled={busy===item.id} onPress={()=>act(item,'cancel')}/>:null}</View></View>)}</View></ScrollView><AppDialog {...dialog} onClose={()=>setDialog(d=>({...d,visible:false}))}/><FeatureTour steps={tourSteps} visible={tourOpen} onClose={closeTour} onStepChange={step=>scrollToSection(step.key)}/></>}
const baseStyles=StyleSheet.create({content:{width:'100%',alignSelf:'center',padding:28,gap:18,paddingBottom:70},desktop:{maxWidth:950},headerRow:{flexDirection:'row',alignItems:'flex-start',gap:12,flexWrap:'wrap'},tourButton:{borderWidth:1,borderColor:colors.primary,borderRadius:20,paddingHorizontal:14,paddingVertical:9,backgroundColor:colors.softBlue},tourButtonText:{color:colors.primaryDark,fontWeight:'900',fontSize:13},tourHighlight:{borderWidth:2,borderColor:colors.primary,borderRadius:16,padding:6,margin:-6},eyebrow:{color:colors.primary,fontSize:14,fontWeight:'900',letterSpacing:1},title:{color:colors.ink,fontSize:27,fontWeight:'900',marginTop:5},subtitle:{color:colors.muted,fontSize:16,marginTop:5},panelTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},help:{color:colors.muted,fontSize:14,lineHeight:20,marginTop:5},label:{color:colors.ink,fontWeight:'800',marginTop:12,marginBottom:6},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:8,paddingHorizontal:12,fontSize:16,color:colors.ink,backgroundColor:'#fff'},multi:{minHeight:82,paddingTop:12,textAlignVertical:'top'},rejectInput:{minHeight:68,borderColor:'#efb4b4',backgroundColor:'#fffafa'},rejectionReason:{color:colors.red,fontSize:14,lineHeight:20,fontWeight:'700',backgroundColor:'#fff0f0',borderRadius:8,padding:10,marginTop:10},timeRow:{flexDirection:'row',gap:12},button:{alignSelf:'flex-end',minWidth:190,marginTop:14},section:{color:colors.ink,fontSize:20,fontWeight:'900'},grid:{gap:12},space:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:layout.radius,padding:17},selected:{borderColor:colors.primary,backgroundColor:colors.softBlue},inactive:{opacity:.6},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},grow:{flex:1},spaceName:{color:colors.ink,fontSize:17,fontWeight:'900'},capacity:{color:colors.primary,fontSize:12,fontWeight:'900'},text:{color:'#445466',fontSize:14,lineHeight:20,marginTop:8},rules:{color:colors.muted,fontSize:13,lineHeight:19,marginTop:8},disabled:{color:colors.red,fontWeight:'900',marginTop:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:colors.border,borderRadius:20,paddingHorizontal:13,paddingVertical:9},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{color:colors.ink,fontWeight:'800'},chipTextOn:{color:'#fff'},reservation:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:layout.radius,padding:17},meta:{color:colors.muted,fontSize:13,marginTop:5},badge:{color:'#996500',backgroundColor:'#fff3d6',paddingHorizontal:8,paddingVertical:5,borderRadius:8,fontSize:12,fontWeight:'900'},approved:{color:colors.green,backgroundColor:colors.softGreen},rejected:{color:colors.red,backgroundColor:'#fff0f0'},actions:{flexDirection:'row',justifyContent:'flex-end',flexWrap:'wrap',gap:8,marginTop:14}});
const styles={...baseStyles,...StyleSheet.create({modeRow:{flexDirection:'row',gap:8,marginTop:16},mode:{flex:1,minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#fff'},modeOn:{backgroundColor:colors.primary,borderColor:colors.primary},modeText:{color:colors.ink,fontWeight:'900'},modeTextOn:{color:'#fff'}})};
