import React,{useContext,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {apiRequest} from '../api/client';
import {AuthContext} from '../context/AuthContext';
import {colors,shadow} from '../ui/theme';

export const CURRENT_TERMS_VERSION='2026-08-04';
export default function TermsAcceptance({navigation}:any){const {user,userToken,updateUser,signOut}=useContext(AuthContext);const [checked,setChecked]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');const accept=async()=>{if(!userToken||!checked)return;setLoading(true);setError('');try{const data=await apiRequest<{user:any}>('/auth/terms/accept',userToken,{method:'POST',body:JSON.stringify({accepted:true,version:CURRENT_TERMS_VERSION})});await updateUser(data.user);}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar o aceite.');}finally{setLoading(false);}};return <ScrollView contentContainerStyle={styles.page}><View style={styles.card}><View style={styles.icon}><Text style={styles.iconText}>✓</Text></View><Text style={styles.eyebrow}>PRIMEIRO ACESSO</Text><Text style={styles.title}>Leia e aceite os Termos de Uso</Text><Text style={styles.intro}>Olá, {user?.fullName||user?.username}. Para continuar no Lar em Dia, é necessário confirmar a leitura e aceitação da versão atual dos Termos de Uso.</Text><Pressable onPress={()=>navigation.navigate('LegalDocument',{document:'terms'})} style={styles.read}><Text style={styles.readTitle}>Termos de Uso</Text><Text style={styles.readText}>Abrir e ler o documento completo</Text><Text style={styles.arrow}>›</Text></Pressable><Pressable onPress={()=>setChecked(value=>!value)} style={styles.checkRow}><View style={[styles.checkbox,checked&&styles.checkboxOn]}>{checked?<Text style={styles.check}>✓</Text>:null}</View><Text style={styles.checkLabel}>Li e aceito os Termos de Uso e as regras definidas pelo condomínio responsável pelo meu cadastro.</Text></Pressable>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={!checked||loading} onPress={accept} style={[styles.accept,(!checked||loading)&&styles.disabled]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.acceptText}>Aceitar e continuar</Text>}</Pressable><Pressable onPress={signOut} style={styles.exit}><Text style={styles.exitText}>Não aceito — sair da conta</Text></Pressable><Text style={styles.note}>O aceite será registrado com usuário, versão, data e informações técnicas de acesso.</Text></View></ScrollView>}
const styles=StyleSheet.create({page:{flexGrow:1,backgroundColor:'#f5f7fb',alignItems:'center',justifyContent:'center',padding:20},card:{width:'100%',maxWidth:560,backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:colors.border,padding:28,...shadow},icon:{width:48,height:48,borderRadius:24,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},iconText:{color:'#fff',fontSize:24,fontWeight:'900'},eyebrow:{color:colors.primary,fontSize:12,fontWeight:'900',letterSpacing:1,marginTop:18},title:{color:colors.ink,fontSize:27,fontWeight:'900',marginTop:6},intro:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:12},read:{position:'relative',backgroundColor:colors.softBlue,borderRadius:12,padding:16,marginTop:20},readTitle:{color:colors.primaryDark,fontSize:16,fontWeight:'900'},readText:{color:colors.muted,fontSize:13,marginTop:3},arrow:{position:'absolute',right:17,top:14,color:colors.primary,fontSize:28,fontWeight:'800'},checkRow:{flexDirection:'row',alignItems:'flex-start',gap:12,marginTop:22},checkbox:{width:25,height:25,borderRadius:6,borderWidth:2,borderColor:colors.border,alignItems:'center',justifyContent:'center'},checkboxOn:{backgroundColor:colors.primary,borderColor:colors.primary},check:{color:'#fff',fontWeight:'900'},checkLabel:{flex:1,color:colors.ink,fontSize:14,lineHeight:21,fontWeight:'700'},error:{color:colors.red,fontSize:13,fontWeight:'800',marginTop:13},accept:{minHeight:54,borderRadius:11,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginTop:20},disabled:{backgroundColor:'#aeb9c7'},acceptText:{color:'#fff',fontSize:16,fontWeight:'900'},exit:{alignItems:'center',padding:14},exitText:{color:colors.muted,fontSize:13,fontWeight:'800'},note:{color:colors.muted,fontSize:11.5,lineHeight:17,textAlign:'center',borderTopWidth:1,borderTopColor:colors.border,paddingTop:13}});
