import React,{useCallback,useContext,useEffect,useState} from 'react';
import {Alert,Platform,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {apiRequest,apiUpload} from '../api/client'; import {AuthContext} from '../context/AuthContext'; import {AppButton,EmptyState,Panel} from '../ui/components'; import {colors} from '../ui/theme';
import {useBreakpoint} from '../ui/responsive';
import {FormGrid,FormFieldFull,CardGrid} from '../ui/grid';
type Block={id:string;name:string}; type Type={id:string;name:string}; type Resident={user_id:string;full_name:string|null;cpf:string|null;role:string;is_representative:boolean};
type Owner={user_id:string;full_name:string|null;cpf:string|null};
type Unit={id:string;block_id:string;block_name:string;number:string;unit_type_id:string|null;unit_type_name:string|null;representative_user_id:string|null;representative_name:string|null;residents:Resident[];owners:Owner[]};
type Person={id:string;full_name:string|null;username:string;cpf:string|null};
type ImportResult={total:number;createdBlocks:number;createdUnits:number;duplicates:number;invalid:number;issues:Array<{row:number;message:string}>};
export default function Units({navigation}:any){const {userToken}=useContext(AuthContext);const [blocks,setBlocks]=useState<Block[]>([]);const [units,setUnits]=useState<Unit[]>([]);const [types,setTypes]=useState<Type[]>([]);const [blockName,setBlockName]=useState('');const [blockId,setBlockId]=useState('');const [number,setNumber]=useState('');const [typeId,setTypeId]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
const [pendingFile,setPendingFile]=useState<File|{uri:string;name:string;mimeType?:string}|null>(null);const [importResult,setImportResult]=useState<ImportResult|null>(null);
const [editingBlockId,setEditingBlockId]=useState('');const [editingUnitId,setEditingUnitId]=useState('');
const [people,setPeople]=useState<Person[]>([]);const [addingOwnerUnitId,setAddingOwnerUnitId]=useState('');const [ownerSearch,setOwnerSearch]=useState('');
const load=useCallback(async()=>{if(!userToken)return;setLoading(true);setError('');try{const [u,t,p]=await Promise.all([apiRequest<{blocks:Block[];units:Unit[]}>('/units',userToken),apiRequest<{unitTypes:Type[]}>('/unit-types',userToken),apiRequest<{users:Person[]}>('/users',userToken)]);setBlocks(u.blocks);setUnits(u.units);setTypes(t.unitTypes);setPeople(p.users);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar unidades.')}finally{setLoading(false)}},[userToken]);useEffect(()=>{load()},[load]);
// Posse (unit_ownerships) é separada de moradia — dá visibilidade só leitura
// sobre os débitos da unidade a quem não mora lá (ex.: dono que alugou pra
// outra pessoa). Ver GET /invoices, que já considera essa tabela.
const addOwner=async(unitId:string,userId:string)=>{if(!userToken)return;setLoading(true);setError('');try{await apiRequest(`/units/${unitId}/owners`,userToken,{method:'POST',body:JSON.stringify({userId})});setAddingOwnerUnitId('');setOwnerSearch('');setNotice('Proprietário adicional registrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao registrar proprietário.')}finally{setLoading(false)}};
const removeOwner=async(unitId:string,userId:string)=>{if(!userToken)return;setLoading(true);setError('');try{await apiRequest(`/units/${unitId}/owners/${userId}`,userToken,{method:'DELETE'});setNotice('Proprietário removido da unidade.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao remover proprietário.')}finally{setLoading(false)}};
const createBlock=async()=>{if(!userToken||!blockName.trim())return;setLoading(true);setError('');try{const result=await apiRequest<{message?:string}>(editingBlockId?`/units/blocks/${editingBlockId}`:'/units/blocks',userToken,{method:editingBlockId?'PATCH':'POST',body:JSON.stringify({name:blockName.trim()})});setBlockName('');setEditingBlockId('');setNotice(result.message||'Bloco cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar bloco.')}finally{setLoading(false)}};
const createUnit=async()=>{if(!userToken||!blockId||!number.trim()||!typeId)return;setLoading(true);setError('');try{const result=await apiRequest<{message?:string}>(editingUnitId?`/units/${editingUnitId}`:'/units',userToken,{method:editingUnitId?'PATCH':'POST',body:JSON.stringify({blockId,number:number.trim(),unitTypeId:typeId})});setNumber('');setTypeId('');setBlockId('');setEditingUnitId('');setNotice(result.message||'Apartamento cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar apartamento.')}finally{setLoading(false)}};
const editBlock=(item:Block)=>{setEditingBlockId(item.id);setBlockName(item.name);setError('');setNotice('')};
const editUnit=(item:Unit)=>{setEditingUnitId(item.id);setBlockId(item.block_id);setNumber(item.number);setTypeId(item.unit_type_id||'');setError('');setNotice('')};
const cancelEdit=()=>{setEditingBlockId('');setEditingUnitId('');setBlockName('');setBlockId('');setNumber('');setTypeId('')};
const representative=async(unitId:string,userId:string)=>{if(!userToken)return;setLoading(true);try{await apiRequest(`/units/${unitId}/representative`,userToken,{method:'PATCH',body:JSON.stringify({userId})});await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao definir representante.')}finally{setLoading(false)}};
const confirmDelete=(message:string)=>Platform.OS==='web'?Promise.resolve(window.confirm(message)):new Promise<boolean>(resolve=>Alert.alert('Confirmar exclusão',message,[{text:'Cancelar',style:'cancel',onPress:()=>resolve(false)},{text:'Excluir',style:'destructive',onPress:()=>resolve(true)}],{cancelable:true,onDismiss:()=>resolve(false)}));
const deleteUnit=async(item:Unit)=>{if(!userToken||!await confirmDelete(`Excluir o apartamento ${item.number} do ${item.block_name}?`))return;setLoading(true);setError('');try{const result=await apiRequest<{message:string}>(`/units/${item.id}`,userToken,{method:'DELETE'});setNotice(result.message);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir apartamento.')}finally{setLoading(false)}};
const deleteBlock=async(item:Block)=>{if(!userToken||!await confirmDelete(`Excluir o bloco ${item.name} e suas unidades sem histórico?`))return;setLoading(true);setError('');try{const result=await apiRequest<{message:string}>(`/units/blocks/${item.id}`,userToken,{method:'DELETE'});setNotice(result.message);if(blockId===item.id)setBlockId('');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir bloco.')}finally{setLoading(false)}};
const selectExcel=(event:any)=>{setPendingFile((event?.target?.files?.[0] as File)||null);setImportResult(null);setError('')};
const selectExcelNative=async()=>{const result=await DocumentPicker.getDocumentAsync({type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];setPendingFile({uri:asset.uri,name:asset.name,mimeType:asset.mimeType||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});setImportResult(null);setError('')};
const importExcel=async()=>{if(!userToken||!pendingFile)return;setLoading(true);setError('');try{const result=await apiUpload<ImportResult>('/units/imports/excel',userToken,pendingFile);setImportResult(result);setPendingFile(null);setNotice(`Importação concluída: ${result.createdUnits} unidades e ${result.createdBlocks} blocos criados.`);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao importar planilha.')}finally{setLoading(false)}};
return <ScrollView contentContainerStyle={s.container} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}><Text style={s.eyebrow}>ESTRUTURA</Text><Text style={s.title}>Blocos e apartamentos</Text><Text style={s.subtitle}>Cadastre as unidades, acompanhe quem mora atualmente e defina o representante de cada apartamento.</Text>
<Panel><Text style={s.heading}>Importar blocos e unidades por Excel</Text><Text style={s.meta}>Use um arquivo .xlsx com as colunas Bloco, Unidade e Tipologia. A tipologia deve estar previamente cadastrada no condomínio.</Text>{Platform.OS==='web'?<View>{React.createElement('input' as any,{type:'file',accept:'.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',onChange:selectExcel,disabled:loading,style:{display:'block',marginTop:14,marginBottom:12,width:'100%'}})}{pendingFile?<Text style={s.file}>Selecionado: {pendingFile.name}</Text>:<Text style={s.meta}>Nenhum arquivo selecionado.</Text>}<View style={s.importButton}><AppButton title={loading?'Importando...':'Importar Excel'} onPress={importExcel} disabled={loading||!pendingFile}/></View></View>:<View><Pressable onPress={selectExcelNative} disabled={loading} style={{minHeight:50,marginTop:12,marginBottom:10,borderWidth:1,borderColor:colors.primary,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:colors.softBlue}}><Text style={{color:colors.primary,fontWeight:'900'}}>Selecionar planilha no aparelho</Text></Pressable>{pendingFile?<Text style={s.file}>Selecionado: {pendingFile.name}</Text>:<Text style={s.meta}>Nenhum arquivo selecionado.</Text>}<View style={s.importButton}><AppButton title={loading?'Importando...':'Importar Excel'} onPress={importExcel} disabled={loading||!pendingFile}/></View></View>}{importResult?<View style={s.importResult}><Text style={s.residentName}>{importResult.total} linhas processadas</Text><Text style={s.meta}>{importResult.createdBlocks} blocos criados · {importResult.createdUnits} unidades criadas · {importResult.duplicates} existentes/atualizadas</Text>{importResult.issues.map(issue=><Text key={`${issue.row}-${issue.message}`} style={s.issue}>Linha {issue.row}: {issue.message}</Text>)}</View>:null}</Panel>
<FormGrid columns={{mobile:1,tablet:1,desktop:2}}><Panel><Text style={s.heading}>{editingBlockId?'Editar bloco':'Novo bloco'}</Text><TextInput placeholder="Nome do bloco" value={blockName} onChangeText={setBlockName} style={s.input}/><AppButton title={editingBlockId?'Salvar bloco':'Cadastrar bloco'} onPress={createBlock} disabled={loading||!blockName.trim()}/>{editingBlockId?<Pressable onPress={cancelEdit} style={s.cancelButton}><Text style={s.cancelText}>Cancelar edição</Text></Pressable>:null}</Panel><Panel><Text style={s.heading}>{editingUnitId?'Editar apartamento':'Novo apartamento'}</Text><Text style={s.label}>Bloco</Text><View style={s.options}>{blocks.map(b=><Pressable key={b.id} onPress={()=>setBlockId(b.id)} style={[s.option,blockId===b.id&&s.on]}><Text style={[s.optionText,blockId===b.id&&s.onText]}>{b.name}</Text></Pressable>)}</View><TextInput placeholder="Número do apartamento" value={number} onChangeText={setNumber} style={s.input}/><Text style={s.label}>Tipologia</Text><View style={s.options}>{types.map(t=><Pressable key={t.id} onPress={()=>setTypeId(t.id)} style={[s.option,typeId===t.id&&s.on]}><Text style={[s.optionText,typeId===t.id&&s.onText]}>{t.name}</Text></Pressable>)}</View><AppButton title={editingUnitId?'Salvar apartamento':'Cadastrar apartamento'} onPress={createUnit} disabled={loading||!blockId||!number.trim()||!typeId}/>{editingUnitId?<Pressable onPress={cancelEdit} style={s.cancelButton}><Text style={s.cancelText}>Cancelar edição</Text></Pressable>:null}</Panel></FormGrid><Panel><Text style={s.heading}>Blocos cadastrados</Text><CardGrid columns={{mobile:1,tablet:2,desktop:3}}>{blocks.map(block=><View key={block.id} style={s.manageRow}><Text style={s.residentName}>{block.name}</Text><View style={s.actions}><Pressable onPress={()=>editBlock(block)} disabled={loading} style={s.editButton}><Text style={s.editText}>Editar</Text></Pressable><Pressable onPress={()=>deleteBlock(block)} disabled={loading} style={s.deleteButton}><Text style={s.deleteText}>Excluir bloco</Text></Pressable></View></View>)}</CardGrid></Panel>{error?<Text style={s.error}>{error}</Text>:null}{notice?<Text style={s.notice}>{notice}</Text>:null}
<View style={s.header}><Text style={s.heading}>Unidades cadastradas</Text><Text style={s.count}>{units.length}</Text></View>{!units.length?<EmptyState title="Nenhuma unidade" description="Cadastre um bloco e seu primeiro apartamento."/>:<CardGrid columns={{mobile:1,tablet:2,desktop:3}}>{units.map(u=><View key={u.id} style={s.card}><View style={s.cardTop}><Text style={s.cardTitle}>{u.block_name} · Apartamento {u.number}</Text><View style={s.actions}><Pressable onPress={()=>editUnit(u)} disabled={loading} style={s.editButton}><Text style={s.editText}>Editar</Text></Pressable><Pressable onPress={()=>deleteUnit(u)} disabled={loading} style={s.deleteButton}><Text style={s.deleteText}>Excluir</Text></Pressable></View></View><Text style={s.meta}>{u.unit_type_name||'Sem tipologia'} · {u.residents.length} morador(es)</Text><Text style={s.rep}>Representante atual: {u.representative_name||'não definido'}</Text>{u.residents.map(r=><Pressable key={r.user_id} onPress={()=>representative(u.id,r.user_id)} style={[s.resident,r.is_representative&&s.residentOn]}><Text style={s.residentName}>{r.full_name||'Sem nome'}{r.is_representative?' · Representante':''}</Text><Text style={s.meta}>{r.cpf||'CPF não informado'} · {r.role}</Text></Pressable>)}
<Text style={s.rep}>Proprietários adicionais (só visualizam débitos, não moram aqui): {u.owners.length?'':'nenhum'}</Text>
{u.owners.map(o=><View key={o.user_id} style={s.manageRow}><View><Text style={s.residentName}>{o.full_name||'Sem nome'}</Text><Text style={s.meta}>{o.cpf||'CPF não informado'}</Text></View><Pressable onPress={()=>removeOwner(u.id,o.user_id)} disabled={loading} style={s.deleteButton}><Text style={s.deleteText}>Remover</Text></Pressable></View>)}
{addingOwnerUnitId===u.id?<View style={{marginTop:8}}>
  <TextInput placeholder="Buscar pessoa por nome ou usuário" value={ownerSearch} onChangeText={setOwnerSearch} style={s.input} autoFocus/>
  {ownerSearch.trim().length>=2?people.filter(p=>!u.owners.some(o=>o.user_id===p.id)&&((p.full_name||'').toLocaleLowerCase('pt-BR').includes(ownerSearch.trim().toLocaleLowerCase('pt-BR'))||p.username.toLocaleLowerCase('pt-BR').includes(ownerSearch.trim().toLocaleLowerCase('pt-BR')))).slice(0,6).map(p=><Pressable key={p.id} onPress={()=>addOwner(u.id,p.id)} disabled={loading} style={s.option}><Text style={s.optionText}>{p.full_name||p.username}{p.cpf?` · ${p.cpf}`:''}</Text></Pressable>):null}
  <Pressable onPress={()=>{setAddingOwnerUnitId('');setOwnerSearch('')}} style={s.cancelButton}><Text style={s.cancelText}>Cancelar</Text></Pressable>
</View>:<Pressable onPress={()=>setAddingOwnerUnitId(u.id)} disabled={loading} style={s.editButton}><Text style={s.editText}>+ Adicionar proprietário</Text></Pressable>}
</View>)}</CardGrid>}</ScrollView>}
const s=StyleSheet.create({container:{width:'100%',alignSelf:'center',padding:24,paddingBottom:40},eyebrow:{color:colors.teal,fontWeight:'900',marginBottom:6},title:{color:colors.ink,fontSize: 28,fontWeight:'900'},subtitle:{color:colors.muted,fontSize: 17,lineHeight: 22,marginTop:6,marginBottom:18},forms:{gap:14},heading:{color:colors.ink,fontSize: 19,fontWeight:'900',marginBottom:10},label:{color:colors.ink,fontWeight:'800',marginBottom:7},input:{minHeight: 52,borderWidth:1,borderColor:colors.border,borderRadius:9,paddingHorizontal:12,marginBottom:10},options:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:10},option:{borderWidth:1,borderColor:colors.border,borderRadius:8,paddingHorizontal:10,paddingVertical:8},on:{backgroundColor:colors.primary,borderColor:colors.primary},optionText:{color:colors.muted,fontWeight:'800'},onText:{color:'#fff'},header:{flexDirection:'row',justifyContent:'space-between',marginTop:22},count:{color:colors.primary,fontWeight:'900'},list:{gap:10,marginTop:10},card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:10,padding:14},cardTop:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10},cardTitle:{color:colors.ink,fontWeight:'900',fontSize: 18},meta:{color:colors.muted,fontSize: 15,marginTop:4},rep:{color:colors.primaryDark,fontWeight:'800',marginTop:8,marginBottom:6},resident:{borderRadius:8,backgroundColor:'#f7f9fb',padding:10,marginTop:6},residentOn:{backgroundColor:colors.softBlue,borderWidth:1,borderColor:colors.primary},residentName:{color:colors.ink,fontWeight:'800'},manageRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,borderBottomWidth:1,borderBottomColor:colors.border,paddingVertical:9},actions:{flexDirection:'row',alignItems:'center',gap:7},editButton:{borderWidth:1,borderColor:'#bfd1ea',backgroundColor:colors.softBlue,borderRadius:8,paddingHorizontal:10,paddingVertical:7},editText:{color:colors.primary,fontSize: 14,fontWeight:'900'},cancelButton:{alignItems:'center',paddingVertical:10,marginTop:5},cancelText:{color:colors.muted,fontWeight:'800'},deleteButton:{borderWidth:1,borderColor:'#efb2b2',backgroundColor:'#fff3f3',borderRadius:8,paddingHorizontal:10,paddingVertical:7},deleteText:{color:colors.red,fontSize: 14,fontWeight:'900'},file:{color:colors.primaryDark,fontWeight:'800',marginBottom:10},importButton:{marginTop:10},importResult:{borderTopWidth:1,borderTopColor:colors.border,marginTop:14,paddingTop:12},issue:{color:colors.red,fontSize: 15,marginTop:5},error:{color:colors.red,marginTop:12},notice:{color:colors.green,fontWeight:'800',marginTop:12}});
